### PR TITLE
docs(self-managed): enrich local kubernetes cluster guide

### PR DESCRIPTION
**Pull request by mary-grace**
Based on [this forum post](https://forum.camunda.io/t/local-kubernetes-cluster-using-kind-camunda-cloud-camunda-platform-not-found/41111) it appears we're missing a step in the process.

## What is the purpose of the change

Enrich local Kubernetes cluster guide since it was copied as it is as part of the C8SM docs restructure.

## Are there related marketing activities

No.

## When should this change go live?

No specific date, as soon as possible.

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory.
- [x] My changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

### CODE REVIEW

**Comment by mary-grace** [comment]
@christinaausley - apologies for not associating this with a particular version! I wasn't sure what the proper protocol was when it's not version-specific (already released or future) but also is ideally going to be released with the next version of docs. Let me know if you have any questions, and feel free to edit if there's a more clear way to communicate this!

**Comment by mary-grace** [comment]
@christinaausley - apologies for not associating this with a particular version! I wasn't sure what the proper protocol was when it's not version-specific (whether already released or future) but also is ideally going to be released with the next version of docs. Let me know if you have any questions, and feel free to edit if there's a more clear way to communicate this change.

**Comment by akeller** [comment]
@aabouzaid can you have a look at this feedback and PR?

**Comment by akeller** [comment]
We will likely need to add this to `8.1` as well so it's in the current docs.

**Comment by aabouzaid** [comment]
@mary-grace do you mind if take over this?
because that guide was moved as it is as part of the restructure I did.

So we will need to make more structure (I will do that if it's ok with you).

**Comment by mary-grace** [comment]
@aabouzaid Please do! You know far more about this topic than I do :) Thanks for taking it on!

**Comment by aabouzaid** [comment]
@christinaausley I've updated the PR, and it's ready for review.

**Review by christinaausley — APPROVED** [review]
Just a few minor adjustments to wording/typos for clarity in my latest commit. Let me know if you have any questions about these 👍

**Pull request merged**
