### PR TITLE
Add labels back to guides

### PR DESCRIPTION
**Pull request by akeller**
## Description

Even though I just created #2322, I realized cleaning up the CSS and adding them to ALL the Guides would satisfy my need for structure and consistency. However, I didn't walk through these guides myself, nor did I run them through any "word to time" estimation tool, so I will open this as a draft first.

@christinaausley @jwulf, this would be a good nudge to review the guides sections - reviewing the content, time estimation, and leveling. This is not urgent, and if it disrupts your review plans, feel free to ignore it for now or launch a PR to remove the badges from our guides entirely.

If we decide to proceed with this, we'll need to backport changes to 8.0+. 

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
@akeller We're wrapping up Modeler content this month, and could prioritize and work through Guides in August. Does this timeframe work for you?

Regardless, I'm good with reincorporating these rough estimates for now. Let me know if you'd like me to backport 👍

**Comment by akeller** [comment]
@christinaausley Guides in August would be great!

**Review by christinaausley — APPROVED** [review]

**Comment by akeller** [comment]
@christinaausley, please backport the changes if you are comfortable with these estimates. You can also wait to complete your Guides review if you'd like to make a single large PR with any other changes (or modify this one).

**Comment by christinaausley** [comment]
> @christinaausley, please backport the changes if you are comfortable with these estimates. You can also wait to complete your Guides review if you'd like to make a single large PR with any other changes (or modify this one).

Great! Josh and I are beginning Guides review this week, with plans for changes within a PR within the next two weeks. Can this wait that long?

**Comment by akeller** [comment]
@christinaausley absolutely, no rush at all.

**Comment by christinaausley** [comment]
@akeller Are you comfortable with merging this in? Josh and I can push out a PR before the end of August with backported adjustments as well, alongside our Guides documentation review.

Or, I can just go ahead and backport in this PR if it would make you more comfortable. Just let me know 👍

**Comment by akeller** [comment]
@christinaausley feel free to merge it. When backporting, double-check my estimates. Do they seem realistic? If you walk through the guides, do you spend about that time on them?

**Pull request merged**
