### PR TITLE
docs(users): add limitations/general users

### PR DESCRIPTION
**Pull request by urbanisierung**
Releates https://github.com/camunda-cloud/console/issues/3524

## What is the purpose of the change

Updates `Manage users` page, adds limitations / general users as a new section.

## Are there related marketing activities

No

## When should this change go live?

asap

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by ultraschuppi** [comment]
lgtm

**Review by felix-mueller — APPROVED** [review]

**Comment by felix-mueller** [comment]
@urbanisierung I think it's fine to merge right?

**Comment by ultraschuppi** [comment]
> Is this still in draft intentionally?

sorry, my fault. forgot to undraft this PR while requesting review from you. i guess it is good to go if the editorial part is okayish enough

**Review by christinaausley — APPROVED** [review]
No adjustments on my end for this one 👍

**Pull request merged**
