### PR TITLE
console: HMAC support for cluster alert webhooks

### PR DESCRIPTION
**Pull request by ultraschuppi**
## Description

relates to https://github.com/camunda/product-hub/issues/1528 / https://github.com/camunda-cloud/camunda-cloud-management-apps/issues/1088

## When should this change go live?

_could_ be now, but i do not expect this feature to be adopted super quick, so no need to be stressed

before merging, i will copypasta the stuff into 8.2 as well

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by ultraschuppi** [comment]
@christinaausley this is getting some traction now and we are about to make it to the finish line. as you know: my wording skills are bad, so maybe you can have a look at proper wording at this thing?

**Comment by christinaausley** [comment]
This looks good! Do we need to backport these changes as well?

**Comment by ultraschuppi** [comment]
> This looks good! Do we need to backport these changes as well?

not sure when this actually hits production - i'd love to see this before we do the 8.3 release. in this case i would take care of backporting to 8.2

**Comment by ultraschuppi** [comment]
@christinaausley thanks for you edits - looks a lot better than my initial draft :)

**Comment by ultraschuppi** [comment]
featzre has been shipped: https://github.com/camunda-cloud/camunda-cloud-management-apps/releases/tag/8.2.161

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
