### PR TITLE
docs(supported environments): Mention 7.16.2+ as a supported Elastics…

### PR DESCRIPTION
**Pull request by ManuelDittmar**
…earch version

Remove unsupported version from docs (7.16.x - 7.16.1.x)

When setting up Optimize with e.g. 7.16.1, you will run into issues with following error message:

Elasticsearch version is not supported by Optimize.
Current version of Optimize supports following Elasticsearch versions:
7.10.0+
7.11.0+
7.12.0+
7.13.0+
7.14.0+
7.15.0+
7.16.2+
7.17.0+
Your current Elasticsearch version is: 7.16.1

This is not reflected in the docs.

### CODE REVIEW

**Comment by akeller** [comment]
@christinaausley can you bring this to @megglos and possibly @HanselIdes for awareness? I'm not sure I'm following the changes in the PR.

@ManuelDittmar thank you for your PR! Would you mind resolving the conflicts by merging in the latest changes to `main`? This will help us accept the PR fast once we clarify it with the product engineering team.

**Comment by megglos** [comment]
This makes transparent that Elasticsearch 7.16.0 & 7.16.1 are not supported, they contain a regression that elastic fixed with 7.16.2.

Many thanks for this improvement @ManuelDittmar !

**Comment by akeller** [comment]
@ManuelDittmar please resolve the conflicts so we can merge this PR. If we don't hear from you relatively soon, we will close this PR and make these changes in a fresh PR which won't give you nearly the credit you deserve.

**Review by akeller — DISMISSED** [review]

**Comment by ManuelDittmar** [comment]
Hi @akeller - I resolved the conflict. However seems like the build-docs workflow is not working correctly

**Review by akeller — APPROVED** [review]

**Pull request merged**
