### PR TITLE
docs(operate): add swagger link and description

### PR DESCRIPTION
**Pull request by ralfpuchert**
## What is the purpose of the change

* Add section for Swagger UI link

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — APPROVED** [review]
No adjustments on my end here 👍

**Comment by akeller** [comment]
This is only available for Self-Managed users then? Is there a hosted Swagger implementation for SaaS?

**Comment by ralfpuchert** [comment]
The Swagger-UI is also in SaaS available. For example https://bru-3.operate.ultrawombat.com/c680d69a-1914-4e2e-a678-c160ac2cb76f/swagger-ui.html

**Comment by akeller** [comment]
I'm good to push this as is, but we may need to make this clearer in the future for SaaS users. Great add!

**Pull request merged**
