### PR TITLE
Add important note about Premium SSD v2

### PR DESCRIPTION
**Pull request by wyattfry**
## Description

Adds critical detail/warning that Premium SSD v2 volumes cannot be backed up.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
Hi @wyattfry! Thanks so much for your contribution. Please [sign the CLA](https://github.com/camunda/camunda-platform-docs/pull/2387#issuecomment-1662867203) and we can move forward with review 👍

**Comment by wyattfry** [comment]
> Hi @wyattfry! Thanks so much for your contribution. Please [sign the CLA](https://github.com/camunda/camunda-platform-docs/pull/2387#issuecomment-1662867203) and we can move forward with review +1

Signed.

**Comment by christinaausley** [comment]
@wyattfry Let me know if you need any assistance with making the version changes 👍

**Comment by wyattfry** [comment]
Updated!

**Review by aabouzaid — DISMISSED** [review]

**Comment by akeller** [comment]
Hi @wyattfry, we cannot merge this unless the CLA has your correct information. When I've run into this in the past, I've added my email to the commit (as the bot prompts). Can you have another look at this?

**Comment by aabouzaid** [comment]
@wyattfry the last commit doesn't have the correct info as the previous ones.
```
Author: Wyatt Fry <wyatt@Wyatts-MacBook-Air.local>
Date:   Mon Aug 7 20:48:19 2023 -0400
```

**Review by christinaausley — DISMISSED** [review]

**Comment by christinaausley** [comment]
Circling back here @wyattfry -- happy to get this approved and merged once the CLA is signed. Do you need any assistance here?

**Comment by christinaausley** [comment]
Hi @wyattfry -- do let me know if I can assist you with working in `camunda-platform-docs` or if you have questions about the CLA 👍

**Comment by wyattfry** [comment]
> Hi @wyattfry -- do let me know if I can assist you with working in `camunda-platform-docs` or if you have questions about the CLA 👍

I tried to fix it. How's that?

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
Awesome. Thank you @wyattfry! Any other changes? Otherwise, we'll get this merged in.

**Pull request merged**
