### PR TITLE
switch position of optimize and tasklist in sidebar

### PR DESCRIPTION
**Pull request by christinaausley**
## What is the purpose of the change

Based on feedback from @HanselIdes, the product uses “Operate, Tasklist, Optimize” in that order but our docs switch Optimize and Tasklist. This PR fits the ordering of the documentation with the existing ordering in the product.

## Are there related marketing activities

No, but I'm anticipating merge conflicts with https://github.com/camunda/camunda-platform-docs/pull/1439 to resolve.

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by HanselIdes — DISMISSED** [review]
lgtm!

**Review by akeller — CHANGES_REQUESTED** [review]
You missed one place to update this, in the `Next` version of the Optimize docs. 

`optimize_sidebars.js` is the file you are looking for, but if you run the docs locally without this change you'll see the sidebar placement jump around if you click into Optimize content in Components on `Next`.

**Comment by christinaausley** [comment]
> You missed one place to update this, in the `Next` version of the Optimize docs.
> 
> `optimize_sidebars.js` is the file you are looking for, but if you run the docs locally without this change you'll see the sidebar placement jump around if you click into Optimize content in Components on `Next`.

@akeller Nice catch 👍 Adjusted in latest commit.

**Review by akeller — APPROVED** [review]

**Comment by akeller** [comment]
@christinaausley I'll let you merge this when you are ready since I know you were concerned there might be some sneaky merge conflicts.

**Pull request merged**
