### PR TITLE
Adjust Inbound Webhook Connectors docs

### PR DESCRIPTION
**Pull request by chillleader**
## What is the purpose of the change

We're getting ready to launch Inbound Webhook Connectors in SaaS. We introduce a couple of improvements that need to be listed in the documentation.
- **Webhooks** tab was in the Web Modeler. It is now referenced in the docs.
- Updated screenshots to match the latest element templates.
- Additionally, I reworked the sections that mention Webhook URLs and how they are composed.

❗  **Important:** inbound Connectors are compatible with Camunda Platform 8.1+ , so I removed the respective documentation from 8.0.

🔜 Documentation related to creating custom Inbound Connectors will be added in a separate PR.

## Are there related marketing activities

_Are there any marketing activities related to the related feature or component? If so, please briefly describe them._

## When should this change go live?

After March 14, 2023

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
> ❗ Important: inbound Connectors are compatible with Camunda Platform 8.1+ , so I removed the respective documentation from 8.0.

Thank you for this important change and call out!

**Review by christinaausley — DISMISSED** [review]
Technical review in latest commit 👍  Bolded references of UI elements and spelled out Camunda Platform 8. Thank you for this!

**Comment by chillleader** [comment]
I spend quite some time figuring out why the build is failing. The error says:
```
Provided URLs failing:
http://172.17.0.2:8080/docs/8.0/components/connectors/out-of-the-box-connectors/github-webhook/ (HTTP 404)
http://172.17.0.2:8080/docs/8.0/components/connectors/out-of-the-box-connectors/http-webhook/ (HTTP 404)
```
In reality, the whole project has no reference to these specific `8.0` paths.

I concluded that this happens because the crawler that checks the link URLs in the build pipeline downloads `sitemap.xml` from production instead of using the sitemap generated during the build. In this PR I have removed 2 pages still present in the sitemap from prod. I wonder if this behavior is intended.

I see 2 options here:
- either merge the PR and release the docs, and then the pipeline will (hopefully) be fixed by itself because of the sitemap update
- or change the build pipeline so that it uses the new sitemap instead of the one from prod

Any opinions?

**Comment by igpetrov** [comment]
Weird. I looked it myself too and I couldnt find any `8.0` ref in relation to inbounds. Shall we rebase branch and see what happens?

**Comment by chillleader** [comment]
> Shall we rebase branch and see what happens?

Didn't help 🙃 I think the issue should go away when we deploy the new docs, and the deployed sitemap gets updated.

**Comment by igpetrov** [comment]
> > Shall we rebase branch and see what happens?
> 
> Didn't help 🙃 I think the issue should go away when we deploy the new docs, and the deployed sitemap gets updated.

I am a bit concerned that the next PR publisher will have the same issue.
I guess, the cheapest way would be doing what you suggested and roll it back if it causes issues.

I don't have merge permissions though, so you might want to talk to somebody from team who owns this repo.

**Review by igpetrov — DISMISSED** [review]
Approving, since I looked it myself and didn't find any cause of the problem. I have a good faith that it might be some caching or related issue.

**Comment by akeller** [comment]
@christinaausley @pepopowitz can you have a look at this build issue?

**Comment by akeller** [comment]
My guess is you renamed or removed pages in this PR that need a redirect.

**Comment by pepopowitz** [comment]
> My guess is you renamed or removed pages in this PR that need a redirect.

Yes -- pages were removed, in which case we should provide a sensible redirect for the removed pages by adding rules to the .htaccess file.

**Comment by christinaausley** [comment]
@chillleader I see you have a commit complete and build running, but let me know if you ever need any assistance with redirects 👍

**Review by igpetrov — APPROVED** [review]

**Pull request merged**
