### PR TITLE
docs(content): remove exporters from components

### PR DESCRIPTION
**Pull request by christinaausley**
## What is the purpose of the change

Resolves https://github.com/camunda/developer-experience/issues/41. Based on [Slack conversation](https://camunda.slack.com/archives/C026U8GBNSW/p1675956532600979), it seems exporters content somehow slipped its way into C8 SaaS content, which requires removal.

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by akeller — APPROVED** [review]
Great spot @christinaausley! Hopefully this takes care of the rogue Exporters page for good! 🤞

**Comment by akeller** [comment]
Just noticed the build was failing, which is surprising because I thought we had redirects for this content already. 🤔

**Review by upgradingdave — DISMISSED** [review]
Looks good, I think exporters page should show up in left now when you search, thanks much!

**Comment by christinaausley** [comment]
> Just noticed the build was failing, which is surprising because I thought we had redirects for this content already. 🤔

@akeller Will take a look at this today 🤔

**Comment by christinaausley** [comment]
Several things here @akeller, I'm surprised this wasn't flagging sooner.

1. We didn't have redirects for `next` and `8.1` yet.
2. The redirects we _did_ have referred to `components/zeebe/technical-concepts/exporters` rather than `components/zeebe/open-source/exporters`.

Adjusted now 👍

**Comment by akeller** [comment]
@christinaausley related to this - https://github.com/camunda/camunda-platform-docs/issues/1397

**Review by akeller — APPROVED** [review]

**Pull request merged**
