### PR TITLE
docs: describe super user mode

### LINKED ISSUE #1901: Document Super Admin Mode in Web Modeler for Org Owners

### PR DESCRIPTION
**Pull request by pihme**
## What is the purpose of the change

Describe super-user mode

closes #1901 

## Are there related marketing activities

No.

## When should this change go live?

When Frontend code of https://github.com/camunda/web-modeler/issues/3781 is deployed to production.

This is a bit of a hen and egg situation. The frontend UI contains a link to the new heading in the documentation, and the documentation describes a feature which does not yet exist. If it weren't for the release, I would be fine with having it merged as "Next". However, since the release is immanent, I would propose to hold it back until the release, then merge it into the "next" section of the documentation.

## Review hints
Please have a look regarding gender neutral language. I tried "they" but since the owner is only one person, it felt strange, so I went with "she or he", which also feels strange

Please give feedback on whether you think a screenshot is needed. I didn't include it, due to hen and egg problem. Also the screenshot would break the reading flow. This extra section is deliberately very short, because it describes an edge cases. If the **owner** finds the button in the UI, there will be a tool tip with the link to this section. (See https://github.com/camunda/modeler-design/issues/161#issuecomment-1458276967) However, if the **owner** reads this documentation and wants to know where to find the button, then there currently is no help. So the dilemma is that this section describes a rare edge case, which is why it is short. But even if you would make it a little longer, it would not warrant a page of its own, in my opinion.

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
> This is a bit of a hen and egg situation. The frontend UI contains a link to the new heading in the documentation, and the documentation describes a feature which does not yet exist. If it weren't for the release, I would be fine with having it merged as "Next". However, since the release is immanent, I would propose to hold it back until the release, then merge it into the "next" section of the documentation.

I am good with keeping this on `hold` for now 👍 

> Please have a look regarding gender neutral language. I tried "they" but since the owner is only one person, it felt strange, so I went with "she or he", which also feels strange.

"They" is totally fine and perfectly accurate here.

> Please give feedback on whether you think a screenshot is needed. I didn't include it, due to hen and egg problem. Also the screenshot would break the reading flow. This extra section is deliberately very short, because it describes an edge cases. If the owner finds the button in the UI, there will be a tool tip with the link to this section. (See https://github.com/camunda/modeler-design/issues/161#issuecomment-1458276967) However, if the owner reads this documentation and wants to know where to find the button, then there currently is no help. So the dilemma is that this section describes a rare edge case, which is why it is short. But even if you would make it a little longer, it would not warrant a page of its own, in my opinion.

I am fine with leaving out the screenshot for now given how short this section is. With a good UI, we shouldn't need one. Can keep an eye on this to see if users struggle to locate this, however.

**Review by christinaausley — APPROVED** [review]
Approving from a technical perspective, but did apply a `hold` label until we are ready to merge.

**Comment by pihme** [comment]
@christinaausley I would propose we merge this now under "next"

**Comment by christinaausley** [comment]
@akeller As this is for `next` now, are we clear to merge?

**Comment by akeller** [comment]
Sounds good to me!

**Pull request merged**
