### PR TITLE
add front matter values to meta

### PR DESCRIPTION
**Pull request by christinaausley**
## Description

Closes https://github.com/camunda/developer-experience/issues/23#issuecomment-1688968868, and pulls front-matter details (already existing in Confluence) out to the docs repo.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by akeller — COMMENTED** [review]
Did you mean to leave off a short description for `keywords`?

**Comment by christinaausley** [comment]
> Did you mean to leave off a short description for `keywords`?

@akeller Adjusted the little note that fell off 👍

**Review by akeller — APPROVED** [review]
Non-blocking, but I've noticed a tendency for teams to follow our instructions exactly at times. Only the title and id is required (to my knowledge). Do you want to mark any as optional? Particularly for keywords, we may add or remove keywords based on marketing and SEO experiments, so we don't necessarily need an exhaustive list when the page is published or updated.

**Comment by christinaausley** [comment]
> Non-blocking, but I've noticed a tendency for teams to follow our instructions exactly at times. Only the title and id is required (to my knowledge). Do you want to mark any as optional? Particularly for keywords, we may add or remove keywords based on marketing and SEO experiments, so we don't necessarily need an exhaustive list when the page is published or updated.

Cool! I'll add a backlog item for this.

**Comment by christinaausley** [comment]
Yes! I'll pop an (optional) tag in there in a subsequent PR.

**Pull request merged**
