### PR TITLE
docs(connectors): introduced Kafka doc

### PR DESCRIPTION
**Pull request by igpetrov**
## What is the purpose of the change

We are introducing a new OOTB Connector - Kafka. This is a user manual for it.

## Are there related marketing activities

N/A

## When should this change go live?

Second half of 22Q4.

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by igpetrov** [comment]
@MoAtCamunda please review

**Comment by igpetrov** [comment]
As of now, put on `hold` until QAs give green light.

**Comment by christinaausley** [comment]
@igpetrov Let me know if you need any assistance with the merge conflicts. Once resolved, I'll give this a final technical review 👍

**Review by mbiciin — COMMENTED** [review]
Looks great!

**Review by christinaausley — APPROVED** [review]
Minor grammatical adjustments in my latest commit. Let me know if you have any questions about these 👍

**Comment by igpetrov** [comment]
Thank you @christinaausley for reviewing it. This one is ready for merge now. Could you please merge it if possible?

**Pull request merged**
