### PR TITLE
Adjust docs for Tasklist `claimTask` mutation

### PR DESCRIPTION
**Pull request by sdorokhova**
## What is the purpose of the change

Within https://github.com/camunda/tasklist/issues/2221 we add new parameter to `claimTask` mutation. 
Therefore:
* generated the new docs for Tasklist API.
* adjusted the Note that we had introduced within #1442 . I decided not to include custom formatting (`:::note`) to our schema file.

It looks like the plugin that we use to generate the docs has changed the output formatting, that's why we have a lot of changes in this PR. But the meaningful changes are only in this commit: https://github.com/camunda/camunda-platform-docs/pull/1495/commits/165958bdd1c7d08149268ebb32f8b1799c2c425f

## Are there related marketing activities

-

## When should this change go live?

May be merged and released after Camunda 8.2.0-alpha2 release (scheduled December 8). 

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by sdorokhova** [comment]
TODO: backport to 8.1

**Review by ralfpuchert — APPROVED** [review]
Puh,a lot of technical changes. I read and tested the generated documentation locally. LGTM!

**Review by christinaausley — APPROVED** [review]

**Comment by akeller** [comment]
@sdorokhova is this ready to merge and release today?

**Comment by sdorokhova** [comment]
@akeller , not yet! We will release 8.2.0-alpha2 next week (December 8). Sorry, I put the wrong date in my precious comment

**Comment by akeller** [comment]
@sdorokhova no problem, this is why I asked 😄

**Comment by akeller** [comment]
Based on an internal notification, this looks like it was released. I will merge and confirm before doing a docs release.

**Pull request merged**
