### PR TITLE
Update amazon-eks.md

### PR DESCRIPTION
**Pull request by felix-mueller**
## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by jessesimpson36 — APPROVED** [review]

**Comment by christinaausley** [comment]
@felix-mueller Let me know if I can assist at all with this 👍

**Comment by jessesimpson36** [comment]
Niiiice! One of my tasks for the AWS Marketplace topic is to make a configuration for the AWS EKS.  Perhaps I can review that section of the documentation as I try to do so, as well as reviewing this PR.

**Comment by jessesimpson36** [comment]
I think backporting to earlier versions makes sense.  at least 8.2.

**Comment by akeller** [comment]
@felix-mueller @jessesimpson36 I added this to 8.2 and made a few tweaks. Is there any additional work here?

**Comment by jessesimpson36** [comment]
No @akeller ,  The patch seems fine to me. There might be more EKS notes for me to add when I actually get permissions to create an EKS cluster, but that's irrelevant to this patch.  :+1: from me!

**Review by jessesimpson36 — APPROVED** [review]

**Review by christinaausley — APPROVED** [review]
Good with this 👍

**Pull request merged**
