### PR TITLE
Update building-flexibility-into-bpmn-models.md

### PR DESCRIPTION
**Pull request by yT0n1**
Is supported in 8.1? https://docs.camunda.io/docs/components/modeler/bpmn/terminate-events/

## What is the purpose of the change

_Briefly describe the change you are making, this helps the reviewer by providing an overview._

## Are there related marketing activities

_Are there any marketing activities related to the related feature or component? If so, please briefly describe them._

## When should this change go live?

_Does this change need to be released before a certain date or milestone? If so, when?_

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@christian-konrad, @berndruecker can I get a quick review here? Or can you add the best reviewer?

**Review by akeller — COMMENTED** [review]
Found the [PR](https://github.com/camunda/camunda-platform-docs/pull/1315) for confirmation! 

Thanks @yT0n1! Appreciate the PR. Would you be willing to add your change to the `next` docs? This will ensure the change propagates to future versions of our docs.  The file is [here](https://github.com/camunda/camunda-platform-docs/blob/main/docs/components/best-practices/modeling/building-flexibility-into-bpmn-models.md).

Otherwise, I'll assign someone from my team to take care of this for you.

**Comment by pepopowitz** [comment]
FYI I've merged `main` into this branch, to take advantage of #1658, and make sure `build-docs` doesn't fail if more changes are pushed here.

**Comment by akeller** [comment]
> Thanks @yT0n1! Appreciate the PR. Would you be willing to add your change to the `next` docs? This will ensure the change propagates to future versions of our docs. The file is [here](https://github.com/camunda/camunda-platform-docs/blob/main/docs/components/best-practices/modeling/building-flexibility-into-bpmn-models.md).

I added this to the `next` docs.

**Review by akeller — APPROVED** [review]

**Pull request merged**
