### PR TITLE
chore(docs): Optimize FE and BE Release update dependencies

### PR DESCRIPTION
**Pull request by cigdemilhan**

### CODE REVIEW

**Review by RomanJRW — APPROVED** [review]

**Comment by RomanJRW** [comment]
@cigdemilhan - approved the changes, but the build fails so you need to run the prettier part as per the output and make any formatting corrections as suggested before you can merge this 🙂

**Comment by pepopowitz** [comment]
Hi friends!! I want to make sure you're aware of #1115 -- a PR that I plan to merge in the next week. 

It makes some fundamental changes to where our docs are sourced: 
1. 8.0 docs will now be sourced from `/versioned_docs/version-8.0` instead of `/docs`
2. Anything in `/docs` will be presented as the next/unreleased version

### Action required

It looks to me like this PR is intended to update the current 8.0 docs. Assuming that's true, one of these things need to happen: 

1. We need to merge this before I merge #1115. This is my favorite option if the PR is ready, because it means no extra work for any of us 😄 
2. After I merge #1115, we'll need to update this PR to make changes in the `/versioned_docs/version-8.0` folder instead of `/docs`. 

If this PR is intended for future 8.1 docs, we don't need to do anything! After #1115 merges, this PR _will_ be pointing at the unreleased 8.1 docs, and you can merge it at your convenience. 

---

I'll hold off on merging #1115 until at least August 8th, but probably not much after. If someone is able to get this one merged before then, great! If not, I'll assume that @cigdemilhan, as the author of the PR, will update this PR as needed or ask for someone else to update it. 

Thanks! If you have questions or concerns, let me know.

**Comment by cigdemilhan** [comment]
Hi @pepopowitz , I'm working on it and will merge latest today.

**Comment by RomanJRW** [comment]
Hi all 👋 . I think the branch got in a weird state here. I just fixed it but had to create a new [PR](https://github.com/camunda/camunda-platform-docs/pull/1121) because the branch here got deleted it seems.

Thanks for the heads up @pepopowitz 👍 
I agree that option 1 is a preference to avoid the additional work. We'll try to get this merged today so it won't impact your changes in the next few days 🙂 

If there is any further conversation regarding this change, I suggest we move it to the new PR now

**Pull request closed without merging**
