### PR TITLE
Cancel prof plan may 16

### PR DESCRIPTION
**Pull request by jprcoliveira**
## What is the purpose of the change

Adding a new section to the managing plan area for Professional plan

## Are there related marketing activities

Nope :)

## When should this change go live?

As soon as possible as we want 

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by jprcoliveira** [comment]
@christinaausley this is my first venture into a PR in the docs so I hope I did not create too much noise. 
@ultraschuppi will have a look tomorrow AM (Berlin time)

**Comment by jprcoliveira** [comment]
Hi @christinaausley, after a few rookie mistakes using GH and some help from @ultraschuppi this PR should be good to go :)
Just one question that I had: should this go under the manage plan instead? I was not clear on what to put under there but feel free to take it away and move it across if that's the best place.

**Comment by jprcoliveira** [comment]
Since @christinaausley is OOO, @akeller could you offer some guidance on my question above on where to place this article (managing org vs current location)? Asking as I wanted to start working on a few more articles related with billing tomorrow morning so some guidance would be appreciated.

**Comment by akeller** [comment]
@jprcoliveira I would move **Cancel Professional plan subscription** under **Managed your plan**.

I also recommend we have a broader discussion or Google Doc sync on how you want the Professional Plan content to evolve in the docs. Currently, I see many pages with a very small amount of text and a few screenshots, which makes me think the design or experience in the product could be more intuitive, so we don't need docs on these actions.

**Comment by jprcoliveira** [comment]
@akeller I will move it over to the Manage your plan and update the PR.

Regarding your comment, I understand your point but it's a bit of "it's easier said than done". In all these billing items, we have an integration with Chargebee and neither the console team nor Finance has the resources or budget to improve it so the idea is to mitigate it with documentation for now. 

Regardless, I will book some time for us to discuss.

**Comment by akeller** [comment]
@jprcoliveira, don't forget to revisit this PR and move the page.

**Review by akeller — APPROVED** [review]
Looks great @jprcoliveira! Just adding a review since the previous review @christinaausley did was stale. LGTM!

**Pull request merged**
