### PR TITLE
Document job retry backoff

### LINKED ISSUE #964: I can read about job backoff
With Zeebe `8.1`, we added a new feature to specify a backoff when failing a job (https://github.com/camunda/zeebe/issues/164). 

We need to add documentation for it. This included:

- [ ] update the gRPC API docs: https://docs.camunda.io/docs/apis-clients/grpc/#failjob-rpc
- [ ] extend the job worker docs: https://docs.camunda.io/docs/components/concepts/job-workers/#completing-or-failing-jobs

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## What is the purpose of the change

Documents the Job retry backoff mechanism.

closes #964 

## Are there related marketing activities

N/A

## When should this change go live?

8.1.0 release.

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — DISMISSED** [review]
Nice 👍 From a technical writing perspective, no adjustments on my end.

**Review by saig0 — CHANGES_REQUESTED** [review]
@remcowesterhoud thank you for documenting this feature. :+1: 

I have a few suggestions for improvement. Please have a look.

**Comment by remcowesterhoud** [comment]
@saig0 I have applied your comments, please have another look.

**Review by saig0 — APPROVED** [review]
@remcowesterhoud looks good. Thank you. :+1:

**Pull request merged**
