### PR TITLE
Zeebe: Clarify usage of advertised host

### PR DESCRIPTION
**Pull request by jonathanlukas**
## Description

Currently, the advertised host parameter is not clear to everybody.

After some try-and-error, everybody could face out what it is, but we should make it more obvious.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

Just a detail that was unclear for some customers

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

I would to have this reviewed as I am not sure whether my wording is completely correct.

### CODE REVIEW

**Review by akeller — DISMISSED** [review]
This is a very simple change, but I was curious if we want to change it directly in the broker template a well.

**Review by oleschoenburg — DISMISSED** [review]
:wrench: The same setting exists for the gateway too so we might want to change that too.

:upside_down_face: Personally, I find "forwarded" to be a bit confusing in this context and would rather use "advertised". It's sort of a term of art and clearer than "forwarded". For example, searching for "advertised address" and "advertised host" brings up documentation for the same concept in similar software such as Kafka. Searching for "forwarded address" shows results for actual paper mail, not software.

I'd suggest something like "Controls the advertised host (the contact point advertised to other brokers)"

Either way, this is probably splitting hairs so I'm approving anyway.

**Comment by akeller** [comment]
@jonathanlukas any additional thoughts here? We can always revise this language in the future if it causes more confusion. Feel free to merge if you are ready.

**Comment by jonathanlukas** [comment]
Thank you @oleschoenburg for your suggestion.

I have to admit that I found it hard to create a proper wording. I changed it to what you proposed as on reading again, I found the usage of 2 different terms for the same thing confusing.

**Review by oleschoenburg — APPROVED** [review]

**Pull request merged**
