### PR TITLE
docs(chore): update reviewers

### LINKED ISSUE #1119: Update Documentation Guidelines for new reviewers
We've had some EMs and leads move around the components and we need to update the reviewers list.

### PR DESCRIPTION
**Pull request by akeller**
Closes #1119

### CODE REVIEW

**Comment by akeller** [comment]
@christinaausley does this align with your understanding on the engineering side?

**Comment by christinaausley** [comment]
I was under the assumption it was Josh based on [this announcement](https://camunda.slack.com/archives/C0202CZ3PPT/p1658738503909419), but Roman is indeed VP software engineering. Is there a preference?

**Comment by akeller** [comment]
That's Josh's handle, as confusing as it looks 😆

**Comment by christinaausley** [comment]
And with that I need to officially shut down my monitors for the weekend 😀 🥴

**Pull request merged**
