### PR TITLE
docs(self-managed): update helm chart versioning schema

### PR DESCRIPTION
**Pull request by aabouzaid**
## Description

Added the latest helm chart versioning schema updates since it was changed last month.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory.
- [x] I have added changes to the main `/docs` directory (aka `/next/`).
- [x] My changes do not require an Engineering review (already reviewed in [camunda/camunda-platform-helm](https://github.com/camunda/camunda-platform-helm)).
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

### CODE REVIEW

**Review by akeller — COMMENTED** [review]
I'm wondering if this is the best place to put this content. So let me think a bit out loud here 👇 

It looks like it should be communicated in the [Announcement page](https://docs.camunda.io/docs/reference/announcements/) since its a change in product behavior (or installation behavior, in this case). 

Additionally, we have version matrices in our [Supported environments page](https://docs.camunda.io/docs/reference/supported-environments/). We don't mention dates, but we do mention version numbers. 

We could add something about the releases to our [release page](https://docs.camunda.io/docs/reference/release-notes/) as well.

However, if Self-Managed users already know to come to this page (or come to this page as part of onboarding to Self-Managed), having this here as-is makes the most sense. We'd likely want to link or reference the other pages above though.

**Comment by christinaausley** [comment]
Hmmmm...several thoughts here.

On first glance, this makes me think of Announcements. However, will this information get lost here? We could always place this bulk content in Announcements, and direct users via an admonition to this post for their awareness to keep these existing Overview pages clean.

Secondly, could certainly note in release notes/blog.

How do you feel about this @aabouzaid?

**Comment by christinaausley** [comment]
Circling back here @aabouzaid -- let me know if I can help 🚀

**Comment by aabouzaid** [comment]
@christinaausley Thanks for the heads-up :ok_hand: 
@hisImminence will take a look on it soon.

**Comment by akeller** [comment]
After a discussion with @hisImminence, I've reworked this PR a bit to include the various areas discussed in the PR comments. @aabouzaid & @christinaausley, WDYT?

As an FYI, @hisImminence and I are discussing changes to clarify things for users working with Self-Managed, including **Update guides** and more. We'll have separate issues & PRs for these topics and bring folks in to collaborate. I mention this because this content may get reworked again in a future PR, but I'd rather merge this PR, make the content available, and then rework it if necessary.

**Comment by akeller** [comment]
Sorry for the noise on this PR, looks like the dependency updates caused some extra changes.

**Comment by akeller** [comment]
@aabouzaid @hisImminence, are you good with the changes I made here?

**Review by hisImminence — APPROVED** [review]
Thanks @akeller! LGTM 🚀 

Looking forward to give this whole topic more attention :)

**Review by christinaausley — APPROVED** [review]
I am happy with this!

**Pull request merged**
