### PR TITLE
saas-invites: restrict hostnames

### PR DESCRIPTION
**Pull request by ultraschuppi**
## What is the purpose of the change

adding a note about the possibility to restrict hostnames for invites in C8 SaaS - related [pdp](https://github.com/camunda/product-hub/issues/839), [console-ticket](https://github.com/camunda-cloud/console/issues/3875)

## Are there related marketing activities

nope

## When should this change go live?

~as soon as the feature is on prod - will keep the PR in draft as long as this is not done~ nao

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by ultraschuppi** [comment]
feature is on prod

**Comment by ultraschuppi** [comment]
> @christinaausley can you review today so we can do a docs release and get this out the door?

no need to be super stressed about this - it involves CSM do do something and they also just learned about this today.

**Comment by christinaausley** [comment]
@akeller @ultraschuppi Will take a look at this today 👍

**Review by christinaausley — APPROVED** [review]
Adjusted a few typos and some wording in my latest commit. Let me know if you have any questions about these changes.

**Comment by ultraschuppi** [comment]
wonderful - thanks @christinaausley! it is a pleasure to insert semi-baked PR here and be sure it gets into a good shape with your help <3

**Pull request merged**
