### PR TITLE
adding form to bpmn step and link fix

### PR DESCRIPTION
**Pull request by christinaausley**
Based on [Bernd's feedback on the Human Task Orchestration guide](https://github.com/camunda/camunda-platform-docs/issues/862), I've added a step clarifying how to add a form to a BPMN user task, and adjusted a link to point at accurate user task C8 documentation.

### CODE REVIEW

**Review by berndruecker — APPROVED** [review]

**Comment by berndruecker** [comment]
LGTM

**Review by akeller — DISMISSED** [review]
Good catch y'all.

**Comment by akeller** [comment]
@christinaausley don't forget this file is included in #867 so you may end up with merge conflicts. But make sure your changes are reflected when both are merged into master.

**Comment by christinaausley** [comment]
@menski Could you take a look at this build error? Perhaps I'm missing something, but I can't locate why this internal link is failing. I popped in a redirect for a quick patch but that didn't do the trick.

**Comment by menski** [comment]
@christinaausley your fix nearly worked it just add a double `docs/` part at the beginning. I pushed a fix which should resolve the issue https://github.com/camunda/camunda-platform-docs/pull/875/commits/25ac32bba549a1c02149f31adc82dcab922e38e8

**Comment by christinaausley** [comment]
@menski Knew I needed a second pair of eyes after staring at those redirects for too long. Thanks!

**Pull request merged**
