### PR TITLE
docs(connectors): update changes to reflect 8.2 release

### PR DESCRIPTION
**Pull request by igpetrov**
## What is the purpose of the change

With `8.2.0` Camunda and `0.18.0` Connectors releases, there's numerous changes, that have to be reflected in the doc. Those changes are reflected here.

## Are there related marketing activities

None

## When should this change go live?

Anytime

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by chillleader — DISMISSED** [review]
LGTM @igpetrov I also adjusted a few lines to address #1999

**Comment by igpetrov** [comment]
> LGTM @igpetrov I also adjusted a few lines to address #1999

Thanks a lot!

**Comment by igpetrov** [comment]
Hi @christinaausley 

This one is ready to review and merge. Thank you!

**Review by christinaausley — APPROVED** [review]
No changes on this one. Nice work 👍

**Pull request merged**
