### PR TITLE
Zeebe: Document support for default bucket encryption

### LINKED ISSUE #1483: Document support for encrypted buckets for hot backups in Zeebe
We tested manually that Zeebe can use buckets with default encryption to save and restore backups. Since customers are interested in encrypted backups, we should publicly document this.

Internal discussion for context: https://camunda.slack.com/archives/C039ZA5EK51/p1666710704914709

### PR DESCRIPTION
**Pull request by oleschoenburg**
## What is the purpose of the change

Document that Zeebe's S3 Backup Store can use buckets with default encryption enabled. This is important to many users who require encrypted backups.

closes #1483

## When should this change go live?
With the release of 8.2

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by deepthidevaki** [comment]
@oleschoenburg This PR documents compression, not encryption as the title says. I think you actually meant to document encryption. Please update. :slightly_smiling_face:

**Comment by oleschoenburg** [comment]
@deepthidevaki :see_no_evil: looks like i messed up my branches. Sorry, I'll update this PR soon.

**Comment by christinaausley** [comment]
Loop me back in when you're ready for a technical review 👍 Thanks!

**Comment by oleschoenburg** [comment]
@deepthidevaki Please take another look :pray:

**Review by deepthidevaki — DISMISSED** [review]
Thanks. LGTM.

**Review by christinaausley — APPROVED** [review]
Minor adjustments in latest commit with spacing. LGTM!

**Comment by oleschoenburg** [comment]
@deepthidevaki If you could approve again? :pray: I had to resolve some merge conflicts which invalidated the PR approval.

**Comment by akeller** [comment]
@oleschoenburg are you just looking for approval to merge? I'm happy to provide this 😃

**Comment by oleschoenburg** [comment]
@akeller yes exactly 👍 thanks!

**Review by akeller — APPROVED** [review]
🚀

**Pull request merged**
