### PR TITLE
chore(docs): remove C7 only label from Optimize public API docs

### PR DESCRIPTION
**Pull request by RomanJRW**
## What is the purpose of the change

This should never have been labelled as C7 only, so this PR removes the label from the next and previous docs

## Are there related marketing activities

No

## When should this change go live?

It's not urgent. But do we need to release the old docs at some point to see the changes reflected there? What is the process for this?

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — APPROVED** [review]
Thanks for this 👍

**Comment by christinaausley** [comment]
**"When should this change go live?
It's not urgent. But do we need to release the old docs at some point to see the changes reflected there? What is the process for this?"**

@akeller do you have thoughts here?

**Comment by akeller** [comment]
> **"When should this change go live? It's not urgent. But do we need to release the old docs at some point to see the changes reflected there? What is the process for this?"**
> 
> @akeller do you have thoughts here?

@RomanJRW by "old docs" do you mean the ones on docs.camunda.org? They should redirect to docs.camunda.io beginning in 3.8.0. Do you need to make changes to 3.7.0?

**Comment by RomanJRW** [comment]
@akeller / @christinaausley - sorry, to clarify I just mean the `.io` docs dating back to the Optimize versions changed in this PR. I wasn't sure if there was a separate release process to update the versioned docs

**Comment by akeller** [comment]
> @akeller / @christinaausley - sorry, to clarify I just mean the `.io` docs dating back to the Optimize versions changed in this PR. I wasn't sure if there was a separate release process to update the versioned docs

@RomanJRW just one release process for everything 😄

**Pull request merged**
