### PR TITLE
Remove Connectors template.md file from all versions

### PR DESCRIPTION
**Pull request by akeller**
## What is the purpose of the change

Removing template.md file from all versions of Connector's docs since its appearing in the sitemap/search. The team did not provide feedback on this template and may not be using it. Additionally, any future templates would need a strategy to remove them from the sitemap/search, which I don't have time to think about currently.

## Are there related marketing activities

No, but this was raised in ask-documentation as a top hit for internal search.

## When should this change go live?

Probably soon-ish so Connectors marketing doesn't drive people to a poor embedded search experiene.

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
I'm intentionally letting these 404 without redirects.

**Comment by akeller** [comment]
Mmm the build isn't going to let me 404 this, is it... 🙃

**Comment by pepopowitz** [comment]
Do you have any creative ideas on how to make the sitemap link-checking ignore specific URLs for PRs? 

Over-complicating-steve wants to say "hey what if we add a bot that attaches some metadata to the PR, so that the link-checking step can cross-reference that metadata to see which URLs to ignore?" but maybe there is a more obvious and simple way to do that?

**Comment by akeller** [comment]
@pepopowitz add an ignorePattern so it's not in the sitemap? I thought about solving this problem with that, but it felt too hands-on for individual pages. 

Possible to modify the Head component - https://docusaurus.io/docs/markdown-features/head-metadata#customizing-head-metadata

**Comment by pepopowitz** [comment]
> @pepopowitz add an ignorePattern so it's not in the sitemap? I thought about solving this problem with that, but it felt too hands-on for individual pages.

Yeah, the down-side to that is that we have to deploy a change to remove it from the sitemap before the PR will go green.

**Comment by akeller** [comment]
@pepopowitz in this case, instead of 404ing, we can redirect to the Available Connectors overview page. No strong requirements here to make 404 possible.

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
