### PR TITLE
Update zeebe backup docs

### PR DESCRIPTION
**Pull request by deepthidevaki**
## What is the purpose of the change

- Backup is not an experimental feature anymore. So the configuration to enable/disable it is removed. (https://github.com/camunda/zeebe/pull/11780)
- Some smaller improvements to the documentation based on the feedback.

## Are there related marketing activities

No.

## When should this change go live?

With 8.2.0 release

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — APPROVED** [review]
Thank you for noting this! Very minor adjustment in latest commit for punctuation.

**Comment by christinaausley** [comment]
Just double checking, does this change also need to be applied to the current `8.1` version of docs?

**Comment by deepthidevaki** [comment]
> Just double checking, does this change also need to be applied to the current 8.1 version of docs?

Removal of feature flag is only from 8.2. But other improvement to the doc can be applied to 8.1 as well. I will apply those changes. Thanks for reminding.

**Comment by christinaausley** [comment]
Lovely! Let me know if you would like any assistance with this.

**Review by christinaausley — APPROVED** [review]

**Comment by deepthidevaki** [comment]
Thank you @christinaausley

**Pull request merged**
