### PR TITLE
chore(docs): explain management dashboard reports

### PR DESCRIPTION
**Pull request by OmranAbazid**
related to OPT-6475

## What is the purpose of the change

We need to clarify the purpose of each report inside the management dashboard. I am just moving these changes from one of our blog posts to here so that it is easier to find. 

## Are there related marketing activities

No

## When should this change go live?

We have a release on 11th of October i believe, It would be great if these changes are included.

## PR Checklist

- [X] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [X] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [X] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [X] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
Hi @OmranAbazid! To make this PR merge as easy as possible, can you sign the CLA?

**Comment by OmranAbazid** [comment]
> Hi @OmranAbazid! To make this PR merge as easy as possible, can you sign the CLA? 

Should be signed now

**Comment by christinaausley** [comment]
@pepopowitz Should these changes be made in:
Screen Shot 2022-09-26 at 9 51 54 AM

**Comment by pepopowitz** [comment]
@christinaausley my interpretation from this sentence in the PR body: 

> We have a release on 11th of October i believe, It would be great if these changes are included.

is that we want these changes to be part of the upcoming version of Optimize docs, but don't really care about current/past versions. Assuming my interpretation is correct, then I think we only want them in the `optimize/` folder, as is done in this PR.


But that's me doing a whole lot of guessing, and @OmranAbazid please let me know if I'm mis-interpreting 😅

**Comment by OmranAbazid** [comment]
> @christinaausley my interpretation from this sentence in the PR body:
> 
> > We have a release on 11th of October i believe, It would be great if these changes are included.
> 
> is that we want these changes to be part of the upcoming version of Optimize docs, but don't really care about current/past versions. Assuming my interpretation is correct, then I think we only want them in the `optimize/` folder, as is done in this PR.
> 
> But that's me doing a whole lot of guessing, and @OmranAbazid please let me know if I'm mis-interpreting 😅

Yea, that's correct. These documentation changes are for the 3.9.0 release.
@christinaausley We do not need to update the 3.8.0 user guide with these changes.

**Review by christinaausley — CHANGES_REQUESTED** [review]
Nice work here -- minor adjustments in latest commit. The only note I have is that the screenshots are a bit blurry; does it show this way for you as well on build?

**Comment by OmranAbazid** [comment]
> Nice work here -- minor adjustments in latest commit. The only note I have is that the screenshots are a bit blurry; does it show this way for you as well on build?

Thanks for the adjustments @christinaausley. Yea, the dashboard screenshot is a bit blurry. I copied it from our [blog](https://camunda.com/blog/2022/06/camunda-optimize-3-9-0-alpha2-released/)
I could retrieve a bit higher resolution one and replace the old one.
We are planning on replacing the screenshot with an automatically generated one. Once that is done, the screenshot will have a better resolution. I hope this is fine for you.

**Comment by christinaausley** [comment]
@OmranAbazid Excellent! This sounds great to me. Let me know if you need any assistance 👍

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
