### PR TITLE
Update deploy-a-process.md

### PR DESCRIPTION
**Pull request by jschulenklopper**
Obvious typo correction "worklfow" -> "workflow".

### CODE REVIEW

**Comment by christinaausley** [comment]
Thanks for such a great catch @jschulenklopper! I just need to apply this fix to the current and recent versions of docs, and we'll be good to merge!

**Comment by jschulenklopper** [comment]
Oops, not intended to close this one, but I'm assembling affected files in #2363.

**Comment by jschulenklopper** [comment]
> Thanks for such a great catch @jschulenklopper! We just need to apply this fix to the current and recent versions of docs, and we'll be good to merge!
> 
> Could you also apply these changes to the `next`, `8.2`, `8.1`, and `8.0` versions of the docs? Let me know if you would like assistance with this!

@christinaausley, Can't seem to find the same typo in those documentation versions (or am I searching incorrectly)?

**Comment by christinaausley** [comment]
@jschulenklopper Enabled auto-merge in https://github.com/camunda/camunda-platform-docs/pull/2363 as this is the only place to fix -- thank you again!

**Pull request closed without merging**
