### PR TITLE
clarifying deployment in utilizing forms and adjusting UI for BPMN guide

### PR DESCRIPTION
**Pull request by christinaausley**
According to [this Slack thread](https://camunda.slack.com/archives/C026U8GBNSW/p1653386762863739), clarifying Camunda Platform 7 and Camunda Platform 8 references (particularly deployment).

### CODE REVIEW

**Comment by christinaausley** [comment]
@McAlm @NPDeehan Mind passing me a review/approval so I can merge adjustments? Thanks!

**Comment by christinaausley** [comment]
@McAlm @NPDeehan One of you mind taking a quick peek at these adjustments this week for approval and I will merge?

**Comment by christinaausley** [comment]
Looping in @akeller here for review as well so we can get this merged.

**Review by akeller — APPROVED** [review]
I'm good with this. Looks like better differentiate between C8 and C7, with the emphasis or "happy path" clearly on C8.

**Comment by akeller** [comment]
@christinaausley we can marge or wait for one of the other reviewers. Your call 😄

**Pull request merged**
