### PR TITLE
clarify conditional properties availability

### PR DESCRIPTION
**Pull request by p-e-e-t-e-r**
## What is the purpose of the change

[Related Github Issue](https://github.com/camunda/camunda-modeler/issues/3482)

## Are there related marketing activities

_Are there any marketing activities related to the related feature or component? If so, please briefly describe them._

## When should this change go live?

_Does this change need to be released before a certain date or milestone? If so, when?_

## PR Checklist

- [ x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@p-e-e-t-e-r thank you for your contribution! Can you add it to the file in /docs/ as well? This will make it available in `next` and all future versions!

@camunda/modeling-dev, can you please assign a reviewer?

**Comment by nikku** [comment]
Thanks for the initiative @p-e-e-t-e-r. I'll restructure this PR slightly, move the "supported in X" notice up to the beginning of each section, and add the contents to all relevant documentation versions.

**Comment by p-e-e-t-e-r** [comment]
@nikku Sorry, it looks like there was a race condition, just published the update requested by @akeller :)
Please apply changes as you see fit!

**Comment by akeller** [comment]
@nikku did you mean for @p-e-e-t-e-r to make these changes or will you like to do the restructuring yourself?

**Comment by nikku** [comment]
@akeller @p-e-e-t-e-r Please checkout my proposal to improve the situation: https://github.com/camunda/camunda-platform-docs/pull/1795.

Looking through the documentation we lacked these hints in a couple of places.

**Comment by nikku** [comment]
Closing this PR as I'm following up via https://github.com/camunda/camunda-platform-docs/pull/1795.

Thanks for getting the ball rolling @p-e-e-t-e-r!

**Pull request closed without merging**
