### PR TITLE
docs(clustering): update image w/ branding

### PR DESCRIPTION
**Pull request by akeller**
## What is the purpose of the change

Add a new partition/clustering image to the docs.

## Are there related marketing activities

No.

## When should this change go live?

After feedback to confirm this is how we want this image to look and open an issue to move to make other images consistent with branding.

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@megglos I'm not sure if this is something you or your team could give a 👍 on. Please feel free to add someone else as a reviewer.

**Comment by Zelldon** [comment]
The partition id's start at one, so all of these counts need to be added +1 then it is correct.

I guesse the Leader Follower assignement was random?

**Comment by akeller** [comment]
@falko can you address @Zelldon's comment?

**Comment by akeller** [comment]
@falko nudging you here re: Zell's comment above.

**Comment by akeller** [comment]
@Zelldon, Falko is headed out on leave. Can you review this diagram? I incremented all the partitions by 1.

**Review by Zelldon — DISMISSED** [review]
Thanks looks good to me :+1:

**Comment by akeller** [comment]
Forgot this wasn't in the latest versioned docs. Merging this, and will slowly update images with more "on brand" colors and styles.

**Pull request merged**
