### PR TITLE
docs(text reports): add text reports to dashboard edit

### PR DESCRIPTION
**Pull request by misiekhardcore**
related to OPT-6696

## What is the purpose of the change

_Briefly describe the change you are making, this helps the reviewer by providing an overview._

## Are there related marketing activities

_Are there any marketing activities related to the related feature or component? If so, please briefly describe them._

## When should this change go live?

_Does this change need to be released before a certain date or milestone? If so, when?_

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — APPROVED** [review]
Very minor adjustment in latest commit -- looks good!

**Comment by akeller** [comment]
@misiekhardcore is this ready to merge?

**Comment by misiekhardcore** [comment]
I think so, yes

**Comment by RomanJRW** [comment]
@misiekhardcore - Thanks for doing the docs for this feature 💪. As a heads up for future, for PRs in this repo:

- We should assign an Optimize reviewer (in addition to someone from the documentation team) when we are adding documentation for a new feature. The documentation team can help with the structure, format, grammar etc., but the Optimize team are responsible for its correctness in terms of if/how it describes the feature itself
- The PR Checklist in the template for this repo should always be used. With the way that the points are phrased, there is no reason that these boxes should be unchecked after opening a review, assuming that action for each is taken where necessary. This gives the team maintaining this repo a much better indication as to whether something is ready to be merged after a review

I will review this PR, so this is more of a note for future - I will also share with the rest of the team 🙂

**Pull request merged**
