### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by tobiasschaefer**

### CODE REVIEW

**Review by akeller — DISMISSED** [review]
Thank you! Great catch!

**Comment by akeller** [comment]
@pepopowitz do you know why this doesn't PR doesn't execute the build-docs step? Is it because Tobias isn't a member of the org? It would be great if this would run for our external contributors (although for small changes like this, I'm confident the build will be successful).

**Comment by pepopowitz** [comment]
I think it's because our [build-docs action] is triggered on `push`, but Tobias opened the PR from a fork. I am pretty sure I can fix this by adding a [`pull-request` trigger](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) -- I'll mess around with this today!

I think the way this org is set up is that we can't merge until all checks pass, so once I get the action running for forked PRs, we'll want @tobiasschaefer to rebase on main so that it runs the check. Tobias, I'll reach out when we are ready for that! (And PS, thank you for the contribution 😄 )

**Comment by pepopowitz** [comment]
@tobiasschaefer Looking at [your previous PRs](https://github.com/camunda/camunda-platform-docs/pulls?q=is%3Apr+author%3Atobiasschaefer), it looks to me like they've only run the `license/cla` check, not the `build-docs` check: 

image

This makes sense based on how we have our `build-docs` action set up. 

I think the likely scenario for your previous PRs is that we had the ability to merge them without all checks passing. We recently moved this repo from the `camunda-cloud` org to the `camunda` org, and this org is more strict -- it requires all checks to pass before we can merge. The skipping of `build-docs` hasn't affected your PRs until now.

But we'll get this sorted out 😅

**Comment by akeller** [comment]
@pepopowitz do you want me to hold off on merging this until you (maybe) update the build-docs process? Otherwise, I will use my admin powers 🧙‍♀️ and merge.

**Comment by pepopowitz** [comment]
@akeller If it's a rush to get this in, feel free to merge....but if not, I like the idea of waiting until [the build-docs changes](https://github.com/camunda/camunda-platform-docs/pull/955) are merged, and using this PR to prove that forked PRs will run the check.

**Comment by tobiasschaefer** [comment]
Hi @pepopowitz ,

I'm back from vacation and have just rebased against the main branch.

The build started and just failed moments ago. I'll leave it up to you to analyze what is going wrong. I'm quite sure it is not my change.

**Comment by akeller** [comment]
@tobiasschaefer all our builds were failing. Please do a quick merge of `main` and this should pass.

**Comment by tobiasschaefer** [comment]
@akeller : I rebased against `main` and the build is green. Please merge now.

**Review by akeller — APPROVED** [review]
Thank you @tobiasschaefer for working through this with us! Your PRs should be much faster to merge now with working builds 😄

**Pull request merged**
