### PR TITLE
feat(comp/console): add dev cluster reservations

### PR DESCRIPTION
**Pull request by urbanisierung**
## What is the purpose of the change

* New Feature in SaaS: Development Clusters
* Add docs about how to change dev cluster reservations on billing page

## Are there related marketing activities

I guess a blog post is in preparation for this feature.

## When should this change go live?

After Prod Launch of dev clusters, relates https://github.com/camunda-cloud/console/issues/3520

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by urbanisierung** [comment]
@ultraschuppi @christinaausley Would you be so kind to have a look at the new section for the billing page docs? It's just a small section about how to change reservations for development clusters. Thanks!

**Comment by urbanisierung** [comment]
@felix-mueller Please add some feature related docs (what's so special about dev clusters), if you want to see them in the docs as well. I'd like to merge the PR right after the launch on Monday. Thanks!

**Review by ultraschuppi — APPROVED** [review]
lgtm

**Review by christinaausley — APPROVED** [review]
Very minor adjustments in latest commit for capitalization/bolding UI elements 👍

**Comment by ultraschuppi** [comment]
@christinaausley thanks for reviewing! can we get this to prod soonish? feature is already rolled out

**Pull request merged**
