### PR TITLE
Link to new Go getting started guide

### PR DESCRIPTION
**Pull request by npepinpe**
We added a new getting started guide for the Go client, but forgot to update the link in the docs.

One thing to note: the code in the getting started guide on GitHub, and the one here in the docs, differs. I thought about aligning them, but decided against, primarily because the [code on GitHub](https://github.com/camunda/camunda-platform-get-started/tree/main/go) is more of a complete sample application, and the one here in the docs is just showing how to do specific things.

### CODE REVIEW

**Comment by npepinpe** [comment]
Not sure why the build fails when all I did was change some Markdown... :thinking:

**Comment by korthout** [comment]
> Not sure why the build fails when all I did was change some Markdown... 🤔

@npepinpe I don't see a failed build 😕 Merging is blocked because of a missing approval. Is that what you meant?

**Review by korthout — APPROVED** [review]
Thanks @npepinpe LGTM 💯

**Review by christinaausley — APPROVED** [review]

**Comment by npepinpe** [comment]
The build was initially failing because I had forked from master and not main :sweat_smile:

**Pull request merged**
