### PR TITLE
feat: introduce whatsapp connector

### PR DESCRIPTION
**Pull request by igpetrov**
## When should this change go live?

Anytime

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — APPROVED** [review]
Technical review in latest commit 👍

**Comment by akeller** [comment]
@igpetrov should this be released as part of the next alpha? I see it can be released anytime but I wasn't sure if these is something you are still working on or you want merged.

**Comment by igpetrov** [comment]
Hi @akeller,

Thank you for bringing this up. This one is ready to merge: I checked the related features, they are still working.

**Comment by igpetrov** [comment]
@akeller, let me merge it now.

**Pull request merged**
