### PR TITLE
docs(identity): add documentation for group management

### PR DESCRIPTION
**Pull request by Ben-Sheppard**
## What is the purpose of the change
This PR is designed to introduce the user guides supporting how Group management is performed in Identity along with a general definition of a Group in our perspective.

## Are there related marketing activities
No

## When should this change go live?
This change is related to functionality that is in the 8.2 release (April 4th) but it can go live before then (or equally a little after).

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — DISMISSED** [review]
Nice work 👍 Technical review in latest commit.

**Review by dlavrenuek — CHANGES_REQUESTED** [review]
The color on assign members to a group and assign roles to a group screenshots is kind of semi transparent. Might be an encoding issue. Otherwise it looks good

**Comment by Ben-Sheppard** [comment]
Thank you for your review and changes @christinaausley! My latest push dismissed your approval, apologies.

@dlavrenuek good spot on the button opacity, I've now updated the two images in question, the only think I can think is that those screenshots were taken from a different monitor (and therefore a different colour profile) so this is why the images were odd!

**Review by dlavrenuek — APPROVED** [review]
Thank you for the great work, everything looks good from my perspective! 🥇

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
