### PR TITLE
standardize across Zeebe diagrams

### PR DESCRIPTION
**Pull request by christinaausley**
## What is the purpose of the change

Based on the proposed color, font, and styling standards, this PR ensures all Zeebe diagrams not already adhering to these guidelines are updated accordingly for future versions.

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
@npepinpe @Zelldon please note two things:
1. Diagrams have been reorganized in the [Google Drive](https://drive.google.com/drive/u/0/folders/14ecu-ZIXVJsB_wgkk9ZANOlVJO5od-d6) according to how they are in the documentation.
2. While I made an announcement about the [discussed proposal](https://docs.google.com/document/d/1gATpZXVxGiWEF4HfUbpUpQJ8ElyeZROERwiArPX5FRk/edit?usp=sharing) in [Slack](https://camunda.slack.com/archives/CSQ2E3BT4/p1663099742184469), would you prefer to see this documented elsewhere?

Thanks for your help on this!

**Comment by akeller** [comment]
I'm not sure what I can offer as far as a review here, but the images look good 👍

**Review by akeller — APPROVED** [review]

**Review by Zelldon — APPROVED** [review]
So sorry for the late review @christinaausley 

Looks good I also like the structure in the drive. If we have now something we agreed on it totally makes sense to me to document that somewhere. I'm not sure where, maybe in the repo in a README or Contribution guide

**Comment by christinaausley** [comment]
Planning to document this officially tomorrow 👍 Merging.

**Pull request merged**
