### PR TITLE
docs(web-modeler): update the documentation for the problems panel

### PR DESCRIPTION
**Pull request by nithinssabu**
Closes https://github.com/camunda/web-modeler/issues/2843

## What is the purpose of the change

_Briefly describe the change you are making, this helps the reviewer by providing an overview._
The design and behaviour of the problems panel component was updated, hence the documentation also need to be updated.

## Are there related marketing activities

_Are there any marketing activities related to the related feature or component? If so, please briefly describe them._
No.

## When should this change go live?

_Does this change need to be released before a certain date or milestone? If so, when?_
ASAP

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by nithinssabu** [comment]
@christinaausley I am a bit confused here whether I should add the changes only to the `/versioned_docs` directory or if I should also update the changes in the `/docs` directory.

**Comment by nithinssabu** [comment]
Closes https://github.com/camunda/web-modeler/issues/2843

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
@nithinssabu It depends -- If you only want your changes to apply to the `next` version of docs, you can make these changes in `docs`, but if these changes also apply to the current/previous version of docs, I would also make changes in `8.1` and `8.0`.

**Review by christian-konrad — APPROVED** [review]
This is great to read! Thanks

**Pull request merged**
