### PR TITLE
Release 8.1

### PR DESCRIPTION
**Pull request by korthout**
This PR exists to merge all changes specifically for the upcoming minor release version 8.1.

### CODE REVIEW

**Comment by akeller** [comment]
@pepopowitz FYI - since you are working on changes to the versioning process, keep PRs like this in mind. You'll need to coordinate with the eng teams (and in this case, community contributors via this PR). Linking the PR in a comment when you get there should be enough, but I wanted to make sure you were aware 😄 .

**Comment by pepopowitz** [comment]
Hi @korthout!! I want to make sure you're aware of #1115 -- a PR that I plan to merge in the next week. 

It makes some fundamental changes to where our docs are sourced: 
1. 8.0 docs will now be sourced from `/versioned_docs/version-8.0` instead of `/docs`
2. Anything in `/docs` will be presented as the next/unreleased version

### No action required on this PR!

It looks to me like this PR is intended for the future 8.1 docs. Assuming I'm correct, we don't need to do anything with this PR in regards to #1115! After #1115 merges, this PR will be pointing at the "next" version's docs (in the `/docs` folder). You'd be able to merge this at your convenience, rather than waiting until the 8.1 release actually happens.

---

I'll hold off on merging #1115 until at least August 8th, but probably not much after. I'll follow up here and in the #ask-documentation slack channel after I've merged, so that you know it's safe to merge "next" release docs. 

Thanks! If you have questions or concerns, let me know.

**Comment by akeller** [comment]
@christinaausley you may need to help out with this PR to move changes after @pepopowitz merges the versioning changes. You can then ask @korthout and team to review to make sure nothing was missed.

**Comment by korthout** [comment]
>It looks to me like this PR is intended for the future 8.1 docs. Assuming I'm correct,

@pepopowitz You're correct. This PR exists to make sure that we don't forget to merge the long-lived branch with upcoming changes for the 8.1 release.

Let me know if there's anything I should verify, or if you need my help in any way.

**Comment by pepopowitz** [comment]
HI @korthout! I've just merged #1118. That means you can feel free to merge 8.1 changes into the `/docs/` folder at your convenience, as that folder now applies to the "Next" version. 🙌

**Comment by korthout** [comment]
@pepopowitz Do we really need to squash merge this PR? All the commits on it are from individual PRs that were individually reviewed and merged into this branch. I would favor merging this with a merge commit. Do you agree?

**Comment by pepopowitz** [comment]
> I would favor merging this with a merge commit. Do you agree?

That works for me! I don't really have a strong opinion on squashing anyway, and your reasoning makes a lot of sense.

**Comment by korthout** [comment]
@pepopowitz Could you maybe approve this PR, temporarily lift the branch protection for `main` and run:

```
git checkout main
git pull
git merge origin/release_8_1
git push
```

**Review by pepopowitz — DISMISSED** [review]

**Comment by pepopowitz** [comment]
@korthout I approve, but I think @christinaausley still needs to do a review re: our style guide. I've added her as a reviewer.

**Review by christinaausley — DISMISSED** [review]
Very minor adjustments in latest commits and then went ahead and merged main in to get this up to date. LGTM!

**Comment by pepopowitz** [comment]
Looks like I've waited too long to merge and there are some conflicts -- the timer-events conflict looks like something I'm not comfortable resolving myself. @korthout can you take a look at it and I promise that as soon as you resolve it I'll drop everything and get this merged?

**Comment by korthout** [comment]
No worries. I'll look at it next week. Enjoy your weekend :wave:

**Comment by korthout** [comment]
I've resolved the conflicts in bdf1dcc. 

@pepopowitz Please have a look and merge it to `main` (preferably without squash, as discussed).

**Comment by korthout** [comment]
🏎️ Now that's what I call fast!

**Comment by pepopowitz** [comment]
😅 a little too fast! I was expecting GitHub to block me from pushing the merge due to branch protection, but it didn't. I hope CI is green!🤞

**Pull request merged**
