### PR TITLE
fix(redhat-openshift.md): use correct env var name

### PR DESCRIPTION
**Pull request by falko**
I tested together with a prospect in their Open Shift cluster that this is the right configuration.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [x] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by falko** [comment]
This needs backporting to all versions.

**Comment by falko** [comment]
@christinaausley anything else you need from me?

**Comment by akeller** [comment]
@camunda/distribution can you confirm these changes are correct?

**Comment by akeller** [comment]
@johanwelgemoed @marcosgvieira can you confirm these environment variables are correct for Operate and Tasklist config?

**Comment by johanwelgemoed** [comment]
@akeller Looked at it together with Svetlana, she approved from Operate side.

**Review by marcosgvieira — APPROVED** [review]
I confirm that this is correct.

**Comment by akeller** [comment]
Thank you, everyone!

**Pull request merged**
