### PR TITLE
feat(docs): describe multi-instance docs in howto

### PR DESCRIPTION
**Pull request by pepopowitz**
Part of #1116 

## What is the purpose of the change

Updates our howto documentation based on multi-instance documentation. 

Does not include updates to the release procedure, because I'm not sure what changes are included there yet 😅 

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by akeller — APPROVED** [review]
This looks awesome @pepopowitz! Super clear and I ❤️ love ❤️ the links to examples in the **Internal links** section.

**Comment by pepopowitz** [comment]
> Super clear

🙏 I still have this terrible sinking feeling that this is going to cause a lot of friction for engineers, so it's good to hear I've at least described it well.

**Comment by akeller** [comment]
> 🙏 I still have this terrible sinking feeling that this is going to cause a lot of friction & confusion for engineers, so it's good to hear I've at least described it well.

You may want to reach out to @MaxTru about presenting this as a topic during the Engineering All Hands. This assumes engineers outside of Optimize are interested or need to be aware of this change. It ultimately depends on how often they may want to link to Optimize pages from non-Optimize pages. Product All Hands is probably too big of an audience. 

You could also ask @RomanJRW if they have an Optimize team meeting that would be appropriate to attend and solicit feedback on how you could make this easier for them to understand and apply. 

A 3rd option is to hold office hours or a dedicated meeting to walk anyone through this or answer questions. The issue here will always be attendance and time zones. It's not a measure of impact or value if a limited audience (or no one) attends.

**Comment by pepopowitz** [comment]
Thanks for the suggestions. I will reach out to Josh and see about how best to share it with that team. The nice thing is that incorrect linking will usually result in a broken build. I'm curious to see how many questions we get in slack about "why doesn't this work," and I think that will give me a good sense of how much outreach I need to do.

**Comment by RomanJRW** [comment]
I agree, really nice description and makes total sense to me 👍 
I worry about how strictly we will be able to follow this rule (at least initially) with the linking, but as long as the build fails I think this will be fine 🙂

**Pull request merged**
