### PR TITLE
Add play mode

### PR DESCRIPTION
**Pull request by HanselIdes**
## What is the purpose of the change

Add Play to the 8.2 and Next documentation, as it's available for about 99% of our users and was featured in the 8.2 public release presentation

## Are there related marketing activities

This blocks a marketing blogpost that needs documentation to explain for whom Play is available. https://docs.google.com/document/d/1iKBBUybTU6vGrnG1maKkwzWRiJmrSxTGRdiKzNND1uk/edit#

## When should this change go live?

No specific date, although it should be out by EOM

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by HanselIdes** [comment]
@christinaausley "Play mode view" seems repetitive and cumbersome to @inzmtsva and me. I originally proposed removing "view", but backed off my changes because it can be handled independently. Was this added by the DevEx team or by the Web Modeler team?

**Review by christinaausley — COMMENTED** [review]
I think this might just need to be added to the sidebars, and then this should be good to go. Technical review in latest commit 👍

**Comment by akeller** [comment]
For previous Alpha features (most recently the Web Modeler API, for example), we usually include them in `next` only.

I'm ok with including this in both 8.2 and `next` because we clearly define the limitations and meaning of alpha. If users find this unclear, we must remove it from 8.2.

**Review by saig0 — DISMISSED** [review]
LGTM. :+1:

**Comment by saig0** [comment]
:x: Please check the [build failure](https://github.com/camunda/camunda-platform-docs/actions/runs/4796767339/jobs/8532922673?pr=2010) before merging. :warning: 
It seems that the formatted doesn't like the changes in `sidebar.js`.

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
