### PR TITLE
Add Database configuration issue to troubleshooting

### PR DESCRIPTION
**Pull request by jonathanlukas**
## Description

There is a new section required about database configuration.

@christinaausley  If this place is not sufficient, please provide me with a better place for this hint.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [x] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by jfriedenstab — CHANGES_REQUESTED** [review]
Some suggestions to align the wording and formatting with the Web Modeler docs; I also added a link to the database configuration section.

**Comment by jonathanlukas** [comment]
Thank you @jfriedenstab for the suggestions. I committed them.

Can you think of a better place than Troubleshooting for this piece of information?

**Comment by akeller** [comment]
@jonathanlukas we can monitor this and move it or have multiple references since I don't see the _best_ place to put it. I see a couple of options, I'll list below:

* https://docs.camunda.io/docs/self-managed/modeler/web-modeler/configuration/#database (which is linked)
* https://docs.camunda.io/docs/self-managed/modeler/web-modeler/configuration/database/

Did you run into this issue or did a customer? Are there any other areas you would expect to see this? We can also ask support if they have more feedback on this, or like I mention initially, we can merge this and move it as we better understand where users look for this info.

**Comment by jonathanlukas** [comment]
Nah, I think the current place is fine.

A customer had this issue, but they could resolve it on their own.

I am not sure how many customers will actually have the idea of installing identity, keycloak and web modeler to the same database, so I would consider it an edge case, and troubleshooting is good then.

**Review by jfriedenstab — APPROVED** [review]

**Pull request merged**
