### PR TITLE
Clarify acronyms and defaults on backpressure

### PR DESCRIPTION
**Pull request by ingorichtsmeier**
I'm trying to understand how back pressure can be configured. First hurdle are the unknown acronyms RTT and AIMD.

## What is the purpose of the change

Clarify the backpressure calculation

## Are there related marketing activities

no

## When should this change go live?

As soon as possible.

## PR Checklist

- [X] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by pepopowitz — COMMENTED** [review]
👍 these are some helpful additions.

1. I suspect you also want the changes in `docs/self-managed/zeebe.....`, in addition to their current location, so that they apply to all future versions as well.
2. I'm adding @christinaausley to review from the technical writing perspective.

**Comment by ingorichtsmeier** [comment]
> I suspect you also want the changes in docs/self-managed/zeebe....., in addition to their current location, so that they apply to all future versions as well.

My entry point was just "Edit page". Right now, I have no idea, where the page is saved as well. 

Yes, the change should live forever...

**Review by christinaausley — APPROVED** [review]
Technical review in latest commit with some grammatical adjustments. While I was in my code editor, I also went ahead and added these changes to the `next` version of docs.

**Comment by ingorichtsmeier** [comment]
Hey everybody involved, thank you for your support and make this small change even better!

Who will usually press the "Squash and merge" button?

The person who initiated the pull request, the initial reviewer or the approver?

Maybe you have a task in a BPMN process for this action?

**Comment by christinaausley** [comment]
> Who will usually press the "Squash and merge" button?

If the PR is approved by the necessary individuals and complete, you can merge! Otherwise, just let me know when your PR is complete and I can merge for you 👍  Merging now!

**Pull request merged**
