### PR TITLE
docs(ml-dataset): Update the user guide so that the json export and t…

### PR DESCRIPTION
**Pull request by andromaqui**
…he new columns on the raw data report are being documented

relates to: OPT-6424

## What is the purpose of the change

_Briefly describe the change you are making, this helps the reviewer by providing an overview._

## Are there related marketing activities

_Are there any marketing activities related to the related feature or component? If so, please briefly describe them._

## When should this change go live?

_Does this change need to be released before a certain date or milestone? If so, when?_

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
@andromaqui Let me know when you're ready for a technical review 👍

**Review by toco-cam — APPROVED** [review]
Looks good. Thx

**Comment by andromaqui** [comment]
@christinaausley Hey Christina! Sorry if this is an obvious question, I just have an issue with the build since yesterday. More specifically it complain that I should run the "prettier" code formatter, which I downloaded and run on vscode but actually nothing changed.. I am not really sure what the issue could be exactly tbh. Sorry if this is a very obvious problem, I am not that deep in the front end world so it could be I am doing a very obvious mistake.

Additionally, I have added the newly created `ml-dataset.md ` file on the sibars.js and optimize-sidebars.js files, however when running the docs I dont see the change reflected under the "Additional Features" column. Would you maybe have an idea why this happens?

Thank you in advance for the help, I have requested your review on this!

**Comment by christinaausley** [comment]
Hi @andromaqui! You can see some of my technical adjustments in my latest commit to adjust some sentence structure/wording for clarity. Please let me know if you have any questions about these.

As far as prettier goes, @pepopowitz enabled custom formatting for our docs earlier this year. You can see some example details [here](https://github.com/camunda/camunda-platform-docs/issues/883). If you're having issues on your end, just run `npm run format` in your terminal and push those adjustments with your commit.

On build I did note your changes apply to the `Next` version of docs and show up in the sidebar. Are you still seeing an issue with your local build?

**Comment by andromaqui** [comment]
@christinaausley Hello Christina! Right now the build has another issue, do you know what this error means exactly? Would anyone from the docs team be able to help pair on the build issues I am having to get this merged maybe?

**Comment by christinaausley** [comment]
@andromaqui There is a broken link in `ml-dataset.md`:
Screen Shot 2022-12-09 at 8 36 53 AM
The existing file path of `/self-managed/optimize-deployment/rest-api/report/get-data-export` does not exist. Did you mean `optimize/api-clients/optimize-api/report/get-data-export.md`?

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
