### PR TITLE
fix urls

### LINKED ISSUE #1951: Remove fully qualified docs URLs from markdown files
Using fully qualified docs URLs breaks versioning across our documentation site. This URLs do not update if you toggle between versions, the remain pointed at the current version, which is potentially problematic if you are looking at an older docs version.

These need to be corrected for relative URLs. There are roughly 169 instances in 72 files, although be careful with find & replace - some markdown files are not docs content and SHOULD include the fully qualified docs URL.

Bonus - linting should check for this, but is likely outside of the scope of this issue.

### PR DESCRIPTION
**Pull request by akeller**
## What is the purpose of the change

Corrects URLs to relative URLs. Closes #1951.

## Are there related marketing activities

No.

## When should this change go live?

This is a bug but not urgent.

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — APPROVED** [review]
Thank you for this 🥲

**Review by pepopowitz — APPROVED** [review]
WOW, this is epic. THANK YOU for cleaning these up!!!!

**Comment by akeller** [comment]
Maybe an in-line example would be helpful too? I struggled with remembering how to format links to specific sections. 

Since I closed this PR, I can add a item to the board to review existing docs on URLs. If someone gets to that before me, drop a comment or tag this PR so we have a nice paper trail.

**Comment by christinaausley** [comment]
I'll launch an issue, add this to the style guide, and post a note on the style guide update in #ask-documentation in the case there is any confusion or folks have additional questions.

**Pull request merged**
