### PR TITLE
docs: documentation for Tasklist REST API

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## What is the purpose of the change

Adding documentation for developed REST API in addition to existing GraphQL API for Tasklist service in  the scope of:
https://github.com/camunda/product-hub/issues/908 epic and https://github.com/camunda/tasklist/issues/2546 implementation task.

## Are there related marketing activities

_Are there any marketing activities related to the related feature or component? If so, please briefly describe them._

## When should this change go live?

_Does this change need to be released before a certain date or milestone? If so, when?_

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@ce-dmelnych please be sure to sign the CLA since this is your first PR in the docs repo 🙂

**Comment by akeller** [comment]
@christinaausley, @ce-dmelnych created two PRs for us. This one is against your branch with the APIs & Clients tab changes. If you plan to move forward with your changes, this would probably be the one to review and incorporate into your PR. Otherwise, close this one, then review and merge #1875.

**Comment by vsgoulart** [comment]
@ce-dmelnych The only difference between this PR and #1875 is the base branch?

**Comment by christinaausley** [comment]
> @ce-dmelnych The only difference between this PR and #1875 is the base branch?

I was wondering the same thing -- @ce-dmelnych should I just review the PR for `master` and can we close this one?

**Comment by akeller** [comment]
@christinaausley @vsgoulart these should be the same changes, just different bases.

@christinaausley close this one since you still have your branch open.

**Pull request closed without merging**
