### PR TITLE
fix(zeebe): remove trailing slash from rebalance url

### PR DESCRIPTION
**Pull request by romansmirnov**
## What is the purpose of the change

_Briefly describe the change you are making, this helps the reviewer by providing an overview._

Removes the trailing slash from Zeebe's rebalance URL. By upgrading Spring Boot to version 3.x in Zeebe, any request with a trailing will fail with 404.

related to https://github.com/camunda/zeebe/pull/11103

## Are there related marketing activities

_Are there any marketing activities related to the related feature or component? If so, please briefly describe them._

## When should this change go live?

_Does this change need to be released before a certain date or milestone? If so, when?_

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by megglos — APPROVED** [review]
LGTM! Will you also add an announcement on the breaking change in `Reference/Announcements` separately?

**Comment by romansmirnov** [comment]
@megglos, I will create a separate issue, therefore. So that I can focus on the code changes first.

**Comment by akeller** [comment]
No docs review is necessary, but this change is missing from version-8.1. Should I add it? I assume we want to wait for the code to be merged and released before merging and releasing the docs.

**Comment by romansmirnov** [comment]
@akeller, it is not necessary to wait for the code to be merged and released. The endpoint already works without the trailing slash.

> ...but this change is missing from version-8.1. Should I add it?

I don't know what that means, please add it whatever it means 😄

**Comment by romansmirnov** [comment]
Ah, now I got it 😆 Sorry, I was not familiar with the structure of the docs. Yes, we should add it to 8.1 as well. I missed that when searching for the trailing slashes.

**Review by akeller — APPROVED** [review]
:shipit:

**Pull request merged**
