### PR TITLE
archiving(1.2) exclude: delete 1.2 content, part 2: chonky boi

### PR DESCRIPTION
**Pull request by pepopowitz**
This PR contains a lot of removed files! Viewing Changed Files will make you cry.

## Description

The final part of #2188!

Deletes the 1.2 content from `main`. This is the final step in archiving this unsupported version.

Since it's hard to view in the browser, these are the commands I ran before pushing it up: 

```sh
rm -rf ./versioned_docs/version-1.2/
rm ./versioned_sidebars/version-1.2-sidebars.json
```

## When should this change go live?

- [x] I intend to merge this in the next day, after I've deployed the `unsupported/1.2` site to production.
- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by christinaausley** [comment]
`exclude-chonky-boi` 😭

**Review by akeller — APPROVED** [review]
Very big, much delete.

**Comment by pepopowitz** [comment]
(the base changed when I merged #2472, so I re-requested review)

**Review by akeller — APPROVED** [review]
I always get nervous when I see additions in the chonky bois ™️. But this looks good!

**Pull request merged**
