### PR TITLE
Update available-connectors-overview.md

### PR DESCRIPTION
**Pull request by MoAtCamunda**
## What is the purpose of the change

_Briefly describe the change you are making, this helps the reviewer by providing an overview._
Include links to the SM Connectors in the https://docs.camunda.io/docs/components/connectors/out-of-the-box-connectors/available-connectors-overview/

## Are there related marketing activities

_Are there any marketing activities related to the related feature or component? If so, please briefly describe them._
No

## When should this change go live?

_Does this change need to be released before a certain date or milestone? If so, when?_

As soon as reviewd
## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by christinaausley — DISMISSED** [review]
Just uppercased Connectors here, spelled out Camunda Platform 8 in full, and added a period. LGTM 👍

**Comment by akeller** [comment]
This should also be available in the `/docs/` for future versions.

Also, we should use relative URLs for the docs. @MoAtCamunda was this the link you were intending to use? It links to the page you are currently on. Did you mean to link to `/self-managed/connectors-deployment/install-and-start`?

**Comment by akeller** [comment]
@christinaausley please follow up with @MoAtCamunda to get this closed out. Thank you!

**Comment by christinaausley** [comment]
@bastiankoerber Note that I've followed up with @MoAtCamunda and he has no additional changes here. Will loop you in as a reviewer moving forward. Merging 👍

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
