### PR TITLE
Add Modeling Guidance Documentation

### PR DESCRIPTION
**Pull request by philippfromme**
## Description

Adds documentation for the problems shown in the _Problems_ panel. This documentation will be accessible through links shown in the _Problems_ panel.

image

Every problem maps to exactly one page in the documentation, which maps to exactly one lint rule (which reports this problem).

Product Hub Issue: https://github.com/camunda/product-hub/issues/1446

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
Since you are effectively crafting landing pages into the docs for each of these pages, I would provide more guidance and links than you think you need.

For example, on the Called Element page, adding a link or info on what are good names for a Process ID, would be helpful. Even a reminder of the format I could use for a Process ID. 

I would link to the implementation of the rule for those interested, although this could be a v2 if we get feedback that people want this. 

My only hesitation with this is I was expecting the guidance to be more involved. This feels a bit heavy for things that look trivial to fix. Do other rules have more involved guidance, or are we over-documenting this experience? (Over-documenting isn't necessarily bad, but something we want to be cautious and critical of.)

Will this be implemented in Web Modeler as well? If not, we'll need to add a badge or move it to the Desktop Modeler section to make it clear this is only available in Desktop Modeler.

**Comment by akeller** [comment]
For consistency, let's plan to document them all, trivial or otherwise. Thanks for the explanation @philippfromme.

**Comment by philippfromme** [comment]
> For consistency, let's plan to document them all, trivial or otherwise. Thanks for the explanation @philippfromme.

Yes, the plan is to document every rule. I just didn't want to do that before we've decided on how. So my idea is to merge these 6 first and then iterate and document the rest of them.

**Comment by christinaausley** [comment]
Let me know when you would like a technical review as well 👍 Happy to assist.

**Comment by philippfromme** [comment]
@christian-konrad created a product hub issue for this topic explaining the user problem we're trying to solve: https://github.com/camunda/product-hub/issues/1446

**Comment by philippfromme** [comment]
@nikku Can you have a look and see whether this is in line with what you wanted to have?

**Comment by nikku** [comment]
> I'm not sure what the best approach is here. We're somewhere in between where there is new documentation but I don't want to simply repeat existing documentation so it's quite minimal.

@akeller The goal is to provide a landing page into the documentation with help for quick fixes. Many issues may be trivial to fix, but some may be more involved. My gut feeling is that we should not write additional documentation, but quote/link to existing documentation.

**Comment by akeller** [comment]
@nikku sounds good. I have no real preference in the target app unless we want to try for SaaS consistency. They look similar enough, and the fix is the same 🤷‍♀️

**Comment by philippfromme** [comment]
> My gut feeling is that we should not write additional documentation, but quote/link to existing documentation. So many pages will pretty much look like [#2359 (comment)](https://github.com/camunda/camunda-platform-docs/pull/2359#issuecomment-1650111906).

@nikku Do I understand you correctly that we should not add any documentation but link to existing documentation instead? That would mean closing this pull request and only adding the URLs through `@camunda/linting`.

**Comment by nikku** [comment]
> @nikku Do I understand you correctly that we should not add any documentation but link to existing documentation instead? That would mean closing this pull request and only adding the URLs through @camunda/linting.

No, we miss-understand each other. We want to have a reference, but that reference should not be a new source of knowledge "how input mappings work", for example, but link to respective place in the documentation that describe that. The goal of each reference page should be to (1) establish context so the user can relate + (2) describe how the issue can be fixed.

**Comment by philippfromme** [comment]
@nikku Okay, got that. We're aligned, then. @christinaausley, can we get a technical review?

**Comment by philippfromme** [comment]
This is what the ❌ and ✔️ pattern looks like in a similar linting documentation (ESLint):

image

**Review by christinaausley — APPROVED** [review]
Technical review in latest commit.

**Comment by nikku** [comment]
> https://github.com/camunda/camunda-platform-docs/pull/2359#issuecomment-1669757466

@christinaausley It is clear that we do not have this in any other parts of the documentation, because we're establishing a new pattern here, that shall be exclusively used for the modeling guidance sub pages (cf. https://github.com/camunda/camunda-platform-docs/pull/2359#issuecomment-1650111906, https://github.com/camunda/camunda-platform-docs/pull/2359#issuecomment-1668419144 for what we want to establish). What the original proposal tries to do is to layout a clear structure for rule pages to achieve the following:

* Concisely explain the rule
* Clearly indicate what is wrong (this is where the user is coming from)
* Clearly indicate what is right (this is where the user wants to go => Fix)
* Reference the rule source, so that advanced users get an understanding where this rule is defined (and can be fixed)

With your changes we get rid of most of that, I think:

* You have to search the screenshots for whether there is a lint error or not (no more `Invalid` or `Valid` headers that people would get used to, no stable deep link for "invalid" sections)
* Rule source is encouraged reading (which it should not be, I think)

I propose three things:

* We introduce a `References` section that hosts follow up links (rule source, but also relevant pages to external documentation)
* We more consistently link existing content from the description (do not burry `learn more...` after a wall of screen shots
* We consider to move back to a stable (and recognizable) valid + invalid pattern

**Comment by nikku** [comment]
I've proposed the references section + linking improvements via https://github.com/camunda/camunda-platform-docs/pull/2359/commits/3ab6d25c7c50337ca10c4d8c3e217ab475e0f9d0. What do you think?

Restoring the headers (valid, invalid) to be discussed.

**Comment by christinaausley** [comment]
Great follow-up here @nikku -- I'm good with this! Can always iterate moving forward. Let me know if I can assist 👍

**Comment by philippfromme** [comment]
@akeller This is ready to be reviewed (and merged).

**Comment by nikku** [comment]
> https://github.com/camunda/camunda-platform-docs/pull/2359#issuecomment-1676823651

Hold on @philippfromme.

----

@christinaausley we discussed internally the change you added to [remove the recognizable valid/invalid pattern](https://github.com/camunda/camunda-platform-docs/pull/2359#issuecomment-1669757466).

We think that this significantly degrades the usefulness of these pages, cf. https://github.com/camunda/camunda-platform-docs/pull/2359#issuecomment-1670709095. 

I see three options:

* :one: Move back to `Valid` / `Invalid` headers
* :two: Keep the human readable headings, but add an :x: / :heavy_check_mark: 
* :three: Keep the current version (no special guidance, for consistency)

The first two options would help our users. The third one is what is currently implemented in this PR.

**Comment by christinaausley** [comment]
> > [#2359 (comment)](https://github.com/camunda/camunda-platform-docs/pull/2359#issuecomment-1676823651)
> 
> Hold on @philippfromme 😉.
> 
> @christinaausley we discussed internally the change you added to [remove the recognizable valid/invalid pattern](https://github.com/camunda/camunda-platform-docs/pull/2359#issuecomment-1669757466).
> 
> We think that this significantly degrades the usefulness of these pages, as a user won't be able to quickly related their issue with what is showcased on the page, cf. [#2359 (comment)](https://github.com/camunda/camunda-platform-docs/pull/2359#issuecomment-1670709095).
> 
> I see three options:
> 
> * 1️⃣ Move back to `Valid` / `Invalid` headers
> * 2️⃣ Keep the human readable headings, but add an ❌ / ✔️
> * 3️⃣ Keep the current version (no special guidance, for consistency)
> 
> The first two options would help our users. The third one is what is currently implemented in this PR.

I am good with Option 2 here, as we will still have human readable headings. Let me know if I can assist with popping this back in 👍

**Comment by nikku** [comment]
Thanks @christinaausley. Find a preview of what I'm trying to get into the docs (option :two:) below: 

image

(We re-use our existing iconography, and ensure these icons are stable across different OS and browsers).

**Comment by philippfromme** [comment]
I would love to see these icons in the docs!

**Comment by nikku** [comment]
Restored markers via https://github.com/camunda/camunda-platform-docs/pull/2359/commits/fab6807197a6fcd2310a709688316f180d57a0b7, cf. https://github.com/camunda/camunda-platform-docs/pull/2359#issuecomment-1678562519.

Please have a look @christinaausley.

**Review by christinaausley — APPROVED** [review]
Nice perseverance through this one 👍 I'll ensure the icons are added to the style guide as well!

**Review by nikku — APPROVED** [review]

**Pull request merged**
