### PR TITLE
Indentation of S3 backup properties

### PR DESCRIPTION
**Pull request by vincentgiraud**
According to https://raw.githubusercontent.com/camunda/zeebe/5811219ca30027a6b496b521b11744a1f8b7d99d/dist/src/main/config/broker.yaml.template the s3 and store properties under data backup are indented at the same level. Tested succesfully on a local installation.

## What is the purpose of the change

_Briefly describe the change you are making, this helps the reviewer by providing an overview._

## Are there related marketing activities

_Are there any marketing activities related to the related feature or component? If so, please briefly describe them._

## When should this change go live?

_Does this change need to be released before a certain date or milestone? If so, when?_

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
Hi @vincentgiraud, we won't be able to merge your PR until you sign our CLA. Can you please take care of that?

Additionally, for this change to be available in all future versions, we'll need to make changes to the page in `/docs/`. Could you add this to your PR? Thank you!

**Comment by pepopowitz** [comment]
FYI I've merged `main` into this branch, to take advantage of #1658, and get the `build-docs` workflow (hopefully) succeeding again.

**Comment by akeller** [comment]
> Hi @vincentgiraud, we won't be able to merge your PR until you sign our CLA. Can you please take care of that?
>
> Additionally, for this change to be available in all future versions, we'll need to make changes to the page in /docs/. Could you add this to your PR? Thank you!

@vincentgiraud, giving you another nudge here, can you please sign our CLA?

**Comment by akeller** [comment]
Hi @vincentgiraud, I want to give you one last nudge to sign the CLA before I close this PR. We cannot accept this PR without you taking action.

**Comment by akeller** [comment]
Hi @vincentgiraud, with the other PR merged, I will close this. We'd love to include your PRs in the future, but please remember to sign the CLA.

**Pull request closed without merging**
