### PR TITLE
docs(connectors): Add aws sqs connector FIFO docs

### LINKED ISSUE #1942: Add SQS FIFO docs
This provides some additional documentation for the new FIFO support for SQS queues which is available via https://github.com/camunda/team-connectors/issues/368

### PR DESCRIPTION
**Pull request by sbuettner**
## What is the purpose of the change

Add information about configuration required by the FIFO queue support which closes #1942

## Are there related marketing activities

Not that I am aware of. 

## When should this change go live?

The FIFO support is part of the future release and should be available then.

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by bastiankoerber — DISMISSED** [review]
looks good. Thank you!

**Review by christinaausley — APPROVED** [review]
Technical review in latest commit with minor adjustments 👍

**Comment by christinaausley** [comment]
@sbuettner Typically we would allow auto-merge here, but as we are prioritizing getting the 8.2 docs out the door as quickly as possible, we will follow up with merging this PR shortly 👍

**Review by christinaausley — APPROVED** [review]

**Comment by christinaausley** [comment]
@akeller looping you in for final approval and merge.

**Review by akeller — APPROVED** [review]
Thank you! Sorry for the thrash here.

**Comment by sbuettner** [comment]
@christinaausley Sorry, still learning about the process. Thank you for your adjustments and taking care of this PR!

**Pull request merged**
