### PR TITLE
docs(operate): document resource based permissions

### PR DESCRIPTION
**Pull request by sdorokhova**
## What is the purpose of the change

Document how to configure resource based permissions from Operate side.

## Are there related marketing activities

-

## When should this change go live?

Together with 8.2 release.

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by sdorokhova** [comment]
I added the links to expected Identity docs, as provided by Identity team, but I will double check them, when Identity docs are ready.

**Review by mihail-ca — APPROVED** [review]

**Review by christinaausley — APPROVED** [review]

**Review by christinaausley — CHANGES_REQUESTED** [review]
It looks like there are two links failing here:

` ../../identity/user-guide/authorizations/managing-resource-authorizations/`
` ../../concepts/access-control/resource-authorizations/ `

Which documents are you trying to access here? I'm happy to hop in and adjust the references here.

**Comment by sdorokhova** [comment]
Hey @christinaausley , these links don't exist yet, but they are created in [this PR](https://github.com/camunda/camunda-platform-docs/pull/1897). May be we merge that one 1st and then rebase?

**Comment by akeller** [comment]
🥚 Merging -> https://camunda.slack.com/archives/C026U8GBNSW/p1680812269564129

**Pull request merged**
