### PR TITLE
Create "Operational guides" section, move to Self-Managed 

### LINKED ISSUE #2529: Create Update guide in Self-Managed
Update guides as they exist today are largely for Self-Managed users, but they are decoupled from Self-Managed docs. 

* Create Update guide section in Self-Managed
* Move all existing Update guide content relevant for only Self-Managed users to new section
* ~Ensure its clear (with links and text) that the Update guide experience is split~

### PR DESCRIPTION
**Pull request by akeller**
## Description

Closes #2529. Also, creates a new section called "Operational guides" and moves the following content:

* Update guides (most)
* Backup and restore
* Troubleshooting

Connector SDK update guide moved into Connectors component section.

These changes are only in `/next/` and should be reviewed prior to backporting. We'll also need redirects.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@hisImminence I added you as a reviewer, but I wasn't sure if you would want to add anything to this PR. You can add anything you want! Or you can just review. Your choice 😄

**Review by sbuettner — APPROVED** [review]

**Comment by akeller** [comment]
@christinaausley my plan was to keep this PR in draft until the end of the week while I collected any more feedback, but I think I've heard from most people on this topic already. Do you have any additional feedback? What do you think of these changes?

**Comment by hisImminence** [comment]
Ah very cool 🚀 
Lets get the stone rolling 🤸‍♀️

**Review by hisImminence — APPROVED** [review]

**Comment by christinaausley** [comment]
Wahoo! I'm happy with this 👍

**Review by christinaausley — APPROVED** [review]

**Comment by akeller** [comment]
Since this is a large change, let's roll this out with the next minor. If we get feedback that we need to adjust this for other versions to reduce confusion, we can do that in the future.

**Comment by akeller** [comment]
@christinaausley can I get another 👍 to merge this?

**Review by christinaausley — APPROVED** [review]
Send it ⛷️

**Pull request merged**
