### PR TITLE
chore: update screenshots to modeler v5.2.0

### PR DESCRIPTION
**Pull request by marstamm**
Related to https://github.com/camunda/camunda-modeler/issues/3034.

### CODE REVIEW

**Comment by akeller** [comment]
@marstamm can we merge this now? @pepopowitz is trying to merge #1118 today and I don't want you to get caught with merge conflicts if we can avoid them 😄

**Comment by marstamm** [comment]
@akeller I don't see why we could not merge it 😄

**Comment by akeller** [comment]
I love the energy @marstamm and @philippfromme :shipit:

**Review by akeller — APPROVED** [review]
I see new version numbers in the footer, let's merge!

**Pull request merged**
