### PR TITLE
docs(self-managed): microsoft aks support - continue

### PR DESCRIPTION
**Pull request by aabouzaid**
## What is the purpose of the change

Documenting Microsoft AKS support in Camunda Platform 8 Self-Managed for 8.1 and tidying up Amazon EKS.

## Are there related marketing activities

No.

## When should this change go live?

No specific date, as soon as possible.

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory. (I will add it after the technical review)
- [x] My changes are not for future versions.
- [x] My changes do not require an Engineering review.
- [x] My changes do not require a technical writer review (already reviewed in #1479

### CODE REVIEW

**Comment by akeller** [comment]
@aabouzaid since I merged your other PR too quickly, I want to ask if this one is ready now. If so, I will merge for you 😄

**Comment by aabouzaid** [comment]
@akeller All checklist items are checked, and it's ready :ok_hand: 
It is the left part from the other PR so it's just a copy and paste :grinning:

**Comment by aabouzaid** [comment]
@akeller btw, who should I assign for review when no technical review is needed? :thinking:

**Comment by akeller** [comment]
@aabouzaid you can assign me

**Review by akeller — APPROVED** [review]

**Pull request merged**
