### PR TITLE
feat: introduce modeler categories

### PR DESCRIPTION
**Pull request by nikku**
This introduces relevant categories for parent pages. As a result:

* Breadcrumbs are meaningful
* Unnecessary "About" pages and nesting in the sitebar is avoided

----

capture K4kgls_optimized

capture 3bIp92_optimized

## Description

Adds necessary meta-data to turn sections into categories, fix the breadcrumbs, and avoid unnecessary nesting + about pages in the sidebar.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

----

Related to https://github.com/camunda/developer-experience/issues/109

### CODE REVIEW

**Review by pepopowitz — APPROVED** [review]
👍 this looks great!

I'm going to add another comment about an observation I have, but it is non-blocking for this PR!

**Comment by pepopowitz** [comment]
An observation that is related but should have no impact on this PR -- I noticed from the gif in the body that there is an unordered list on the Modeling Guidance category page, enumerating the Rules within the category. In other docs, [we've used the built-in docusaurus `<DocCardList>` component](https://github.com/camunda/camunda-platform-docs/blob/e72f25f10119cd8650bd5adb7b6d179f4b623842/docs/self-managed/platform-deployment/helm-kubernetes/platforms/platforms.md?plain=1#L14) to enumerate the children without hardcoding them. 

There is an obvious visual difference between these approaches -- a [purely text-based unordered list](https://stage.docs.camunda.io/docs/next/components/modeler/reference/modeling-guidance/) (image 1 below), versus [a list of cards](https://stage.docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/platforms/) (image 2 below). Throw in another variant, [this tabular presentation](https://docs.camunda.io/docs/next/components/modeler/forms/form-element-library/forms-element-library/) (image 3 below). 

My question for @christinaausley -- from a consistency standpoint, how do you feel about these variations? 

And for @nikku -- the cards are very large, and take up a lot of space without adding a ton of information, and I could imagine that influencing your decision to use an unordered list instead. If the cards were more condensed, would you be more inclined to use them?

And for @nikku -- if you feel strongly about using the unordered list, would it be useful to have a component that renders all child pages, without hardcoding them, as an unordered list instead of a list of cards?

### Images

1: unordered list

image

2: card list

image

3. table

image

**Comment by nikku** [comment]
Indeed we could optimize our modeling guidance landing page as you mention in https://github.com/camunda/camunda-platform-docs/pull/2454#issuecomment-1682670842, I don't see it as a big priority though:

* If we go for tiles, then descriptions must be on point. 
* Either way, this page is only there for completeness, and not as a main entry point. Main entry is via individual pages, through the modeler apps.

**Comment by nikku** [comment]
Changed to use `DocCardList` via https://github.com/camunda/camunda-platform-docs/pull/2462. 

We can iterate on this in the future. For now, it ensures that all rules are consistently linked, which is :+1:.

**Pull request merged**
