### PR TITLE
feat(operate/tasklist): document Identity JWT tokens to access APIs

### LINKED ISSUE #915: Document usage of Identity M2M token for Operate API

### PR DESCRIPTION
**Pull request by sdorokhova**
* move docs for JWT tokens for Operate API in the Cloud
* add docs for Identity JWT tokens for Self-managed for Operate API and Tasklist API

closes #915, #916

### CODE REVIEW

**Comment by sdorokhova** [comment]
Identity JWT tokens functionality was backported to 8.0 and released in 8.0.4 -> from what I understand we can merge it to `main` branch and would be nice to publish the docs after this is merged

**Comment by akeller** [comment]
@sdorokhova can you please sign the CLA? Thank you!

**Review by ralfpuchert — APPROVED** [review]

**Comment by akeller** [comment]
@christinaausley can you review this content?

For transparency, I'll approve this without @sdorokhova signing the CLA because they are out (and a Camunda employee anyway).

**Comment by akeller** [comment]
Thanks @christinaausley!

**Pull request merged**
