### PR TITLE
Docs collapse connectors

### PR DESCRIPTION
**Pull request by christinaausley**
## Description

Collapsing Connectors via tabs.

To backport in separate PR once approved.

Closes https://github.com/camunda/camunda-platform-docs/issues/2568.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [x] This change or page is part of a marketing blog, conference talk, or something else on a schedule. CC
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
Adding @sbuettner since Bastian is at CamundaCon and may not be able to review.

**Comment by christinaausley** [comment]
> Adding @sbuettner since Bastian is at CamundaCon and may not be able to review.

Bastian did confirm the structure for me before I got started, so I have a kind of sort of approval 😆

**Review by akeller — APPROVED** [review]
image

It would be good if we could remove the section from the sidebars for areas where we only have one page now. But I see this as a nitpick, so I'm approving.

**Review by sbuettner — APPROVED** [review]

**Comment by christinaausley** [comment]
Merging, though I'll open a separate issue to clean this up.

**Pull request merged**
