### PR TITLE
chore(web-modeler): document new template picker

### PR DESCRIPTION
**Pull request by wollefitz**
Closes https://github.com/camunda/web-modeler/issues/1795

### CODE REVIEW

**Comment by christinaausley** [comment]
@wollefitz Happy to assist with a quick technical review here once you're just about finished with changes.

**Comment by pepopowitz** [comment]
Hi @wollefitz!! I want to make sure you're aware of #1115 -- a PR that I plan to merge in the next week. 

It makes some fundamental changes to where our docs are sourced: 
1. 8.0 docs will now be sourced from `/versioned_docs/version-8.0` instead of `/docs`
2. Anything in `/docs` will be presented as the next/unreleased version

### Action required

I'm not sure if this PR is intended to update 8.0 or 8.1 docs, but if it is 8.0, one of these things need to happen: 

1. We need to merge this before I merge #1115. This is my favorite option if the PR is ready, because it means no extra work for either of us 😄 
2. After I merge #1115, you'll need to update this PR to make changes in the `/versioned_docs/version-8.0` folder instead of `/docs`. 

And if this PR is intended for future 8.1 docs, we don't need to do anything! After #1115 merges, this PR _will_ be pointing at the unreleased 8.1 docs, and you can merge it at your convenience. 

---

I'll hold off on merging #1115 until at least August 8th, but probably not much after. If you are able to get this one merged before then, great! If not, I'll assume you intend to update this PR, or it's intended for the 8.1 docs. 

Thanks! If you have questions or concerns, let me know.

**Comment by marcellobarile** [comment]
@pepopowitz I'm taking over this task since @wollefitz is on parental leave. I'm also going to gather more information about the target version (8.0 vs 8.1), that's something that I don't know. I keep you posted.

**Comment by pepopowitz** [comment]
Thanks for taking this over @marcellobarile! 

I think the build issues on this PR are a result of this branch being a bit out of date -- 28 commits behind `main`. In the last couple weeks we've merged several PRs that moved content around, and that would cause the link-checking to fail in this PR.

You could rebase this branch on `main`, or merge `main` into it -- whichever you prefer.

**Comment by marcellobarile** [comment]
Thank you @pepopowitz, after the merge now the PR builds successfully. While we decide about the version let me send it to @christinaausley for review.
Since this is my first contribution to the public doc, please let me know if further steps need to be taken.

**Review by christinaausley — APPROVED** [review]
Very minor adjustments in latest commit to remove excess spacing and clean up some of the UI elements referenced.

**Review by christian-konrad — APPROVED** [review]
Looking great!

**Pull request merged**
