### PR TITLE
Java Client code example not working

### PR DESCRIPTION
**Pull request by jenshb**
Code example is not working because zeebeApi is not defined. By trial and error figured out, that the Zeebe Adress without Port has to be passed here.

## What is the purpose of the change
Working code example

## Are there related marketing activities
No

## When should this change go live?
No

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@berndruecker is this behavior correct? The address doesn't include the port?

**Comment by jenshb** [comment]
Hi @berndruecker,

I also thought about providing examples, an example says more than thousand words ;-)
In the code example, the zeebeAPI is written into audience and gatewayAddress.
When I set the zeebeAPI to the ZEEBE_ADDRESS provided by Operate on creating a new client (in my case 
ZEEBE_ADDRESS='0f6517db-6973-4604-af18-4f7f2583042a.dsm-1.zeebe.camunda.io:443')
I get an HTTP return code 401. 

As far as I can see, this is because the audience should not contain the port but has to be 
"0f6517db-6973-4604-af18-4f7f2583042a.dsm-1.zeebe.camunda.io". gatewayAddress works with "0f6517db-6973-4604-af18-4f7f2583042a.dsm-1.zeebe.camunda.io:443"

**Comment by christinaausley** [comment]
My renaming work with APIs/clients will likely cause conflicts here. Once you've completed the change, please loop me in if you need assistance with a clean build here.

**Comment by berndruecker** [comment]
Not sure if @jenshb is still working on this? I think we can merge the current proposal, still I personally would prefer an example - not the rule "gateway address without port" - but it is an improvement anyway

**Comment by jenshb** [comment]
I introduced a new variable for _audience_, because it can differ from zeebeApi, and added examples. Maybe it's better now?

**Comment by akeller** [comment]
@berndruecker @jenshb is this still being worked?

**Comment by berndruecker** [comment]
I will merge it now - it makes total sense. @jenshb: Thanks for the improvement of the docs!

**Review by berndruecker — APPROVED** [review]

**Comment by christinaausley** [comment]
@jenshb I think this change also needs to be applied to the next version of docs, then we can merge. Let me know if you need any assistance with this @jenshb!

**Comment by christinaausley** [comment]
@jenshb @berndruecker Do we just need to add this change to versioned docs? Happy to assist with this and merge, but let me know if you were planning to make any other changes here.

**Comment by jenshb** [comment]
@christinaausley I added the changes from the /version_docs directory to the /docs directory. I hope that's what you intended?

**Review by christinaausley — APPROVED** [review]
Thanks all! I'll enable auto-merge and we can wrap this up.

**Pull request merged**
