### PR TITLE
feat: update to Camunda Modeler 5.8.0

### PR DESCRIPTION
**Pull request by nikku**
## What is the purpose of the change

Update screenshots to Camunda Modeler 5.8.

## Are there related marketing activities

No.

## When should this change go live?

Around February 14th.

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
@nikku do you mean for this to still be in draft? Modeler 5.8 is released, [per you](https://camunda.com/blog/2023/02/camunda-desktop-modeler-5-8/) 😄

**Comment by nikku** [comment]
Sorry, not a draft anymore :+1:

**Comment by akeller** [comment]
The current docs are in 8.1, but this PR only includes changes to `next`. If you are still around, can you add them to the 8.1 docs?

**Comment by akeller** [comment]
@nikku I went to backport your changes to the 8.1 docs (the current version) and ran into an issue.

The last 4 images in the PR are in `docs/self-managed/modeler/desktop-modeler/img/*` which doesn't exist in the 8.1 docs. In the [8.1 docs](https://docs.camunda.io/docs/self-managed/web-modeler/installation/) I only see a web-modeler section. 

Is this available today? If so, let's get this corrected in another PR.

CC @christinaausley

**Review by akeller — APPROVED** [review]
I added the images to 8.1, except the images in `/self-managed/`, so we can get this merged.

@christinaausley can you follow up with the Modeler team about the discrepancies between 8.1 and Next for Modeler in `/self-managed/`.

**Comment by nikku** [comment]
@akeller Thanks for detecting this PR, and for getting it merged :1st_place_medal:

**Pull request merged**
