### PR TITLE
docs: update connectors related docs

### PR DESCRIPTION
**Pull request by igpetrov**
## What is the purpose of the change

Keeping connectors doc up-to-date.

## Are there related marketing activities

No.

## When should this change go live?

Any time but no rush; the change is related to released code.

## PR Checklist

- [x] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [x] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by igpetrov** [comment]
This PR is ready to be reviewed and merged.

Added the rest of the team just for visibility.

**Comment by igpetrov** [comment]
Hi @christinaausley,

Just in case notification piled under other emails, could you please take a look at your convenience? It's not urgent at all.
This one is ready to be merged. No other approval required.

**Comment by christinaausley** [comment]
@igpetrov I'll have a look at this today 👍

**Review by christinaausley — APPROVED** [review]
Technical adjustments in latest commit, including uppercase Connectors and lowercase inbound webhook. Let me know if you have any questions about these changes.

**Pull request merged**
