### PR TITLE
feat: move items to Done when they're assigned to someone

### PR DESCRIPTION
**Pull request by pepopowitz**
HOLD! because we're testing it out

## What is the purpose of the change

Eventually: move completed items to Done when they are merged.

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Comment by akeller** [comment]
Do you want me to hold off on manually moving them so you have some items to work with?

**Comment by pepopowitz** [comment]
> Do you want me to hold off on manually moving them so you have some items to work with?

**Comment by pepopowitz** [comment]
Closing this as something about our Developer Experience project is not linked to the repository/owner in a way that the alex-page/github-project-automation-plus workflow can find it. 

Notes from our findings: 

- It [looks for a project based on the current repository or the repository's owner](https://github.com/alex-page/github-project-automation-plus/blob/main/src/generate-mutation-query.js#L14-L18), and the Developer Experience project does not exist in either of those places. See screenshot for graphql query that simulates what the code in the workflow is trying to find (and note that neither of the collapsed results are the Developer Experience project):
   image
- This results in the error `Could not find the column "✅ Done" or project "Developer Experience"` when [running the workflow](https://github.com/camunda/camunda-platform-docs/actions/runs/3743622327/jobs/6356000154).

**Comment by akeller** [comment]
> Closing this as something about our Developer Experience project is not linked to the repository/owner in a way that the alex-page/github-project-automation-plus workflow can find it.

It's an `internal` repo, but it doesn't necessarily have to be in the future. Feel free to bring this to a team meeting if you want to discuss!

**Pull request closed without merging**
