### PR TITLE
docs(operate): backupId type changed to Integer

### PR DESCRIPTION
**Pull request by sdorokhova**
## What is the purpose of the change

Document type of `backupId` changed from String to Integer. I don't think that this is a breaking change, as Zeebe anyway supported only Integer `backupId` in v.8.1 and we recommend to use one and the same `backupId` for all the applications. @christinaausley what do you think? Should we document it as breaking change anyway?

## Are there related marketing activities

-

## When should this change go live?

8.2 release

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by ralfpuchert — DISMISSED** [review]

**Review by christinaausley — APPROVED** [review]
This is only for the `next` version of docs, correct?

**Comment by sdorokhova** [comment]
Hey @christinaausley , I gave it a second thought and reorganized out disclaimer about breaking changes a little bit. Could you please proof-read?

>This is only for the next version of docs, correct?
Yes, exactly

**Review by christinaausley — APPROVED** [review]
Incorporated an admonition and applied technical review in latest commit 👍

**Comment by sdorokhova** [comment]
@christinaausley , sorry, I had to push again to fix indentation, otherwise `note` is not closed properly. If I run `prettier` I get this indentation inserted again, which is wrong. And one of the checks is failing now, because formatting check is not passed. Do you have an idea what to do with it? Can we just ignore that check failure?

And do we need to rebase again now?

**Comment by christinaausley** [comment]
> @christinaausley , sorry, I had to push again to fix indentation, otherwise `note` is not closed properly. If I run `prettier` I get this indentation inserted again, which is wrong. And one of the checks is failing now, because formatting check is not passed. Do you have an idea what to do with it? Can we just ignore that check failure?
> 
> And do we need to rebase again now?

@pepopowitz Do you have thoughts here on the formatting issue? I think we've run into something like this before.

**Comment by sdorokhova** [comment]
@christinaausley I'm leaving on vacation now, could you please take care of this PR and merge it when all checks are green? thank you!

**Comment by christinaausley** [comment]
> @christinaausley I'm leaving on vacation now, could you please take care of this PR and merge it when all checks are green? thank you!

On it! Enjoy your time off!

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
