### PR TITLE
Add SaaS architecture diagram

### PR DESCRIPTION
**Pull request by akeller**
Partially addresses #444.

### CODE REVIEW

**Comment by akeller** [comment]
@christinaausley would love your thoughts here beyond just a review! I thought the image was a bit strange above the text describing the components and then below the components I felt like it needed a little intro sentence.

This does violate some of my emerging thoughts about how to handle images accessibly, but I'm still unsure how to make architecture-like diagrams like this accessible.

**Comment by christinaausley** [comment]
@akeller Are you looking for specific feedback on the diagram?

Based on what you've changed, I do agree we need an introductory sentence (which I've adjusted slightly in my latest commit) and this should definitely be placed as you have it after the components are textually introduced.

As far as accessibility goes, contrasting colors and clear alt text assist. However, here's where things get a little more complex with diagrams...

We do indeed have the option to create accessible PDFs where you write out a brief description of a chart/diagram and provide the accessible document link near the image/clickable on the image. However, if the content on the screen describes the exact same information presented in a diagram and someone who could not see the chart or diagram would not lose any information by not being able to see it, you do not need to provide an accessible document because you have already provided an accessible way of engaging with the information. This all, of course, depends on the level of accessibility we need/want to meet.

**Comment by akeller** [comment]
Thanks for the adjustment to the introductory sentence. That's all I was looking for review-wise right now.

Interesting about the accessibility angle, maybe we can test out the accessible PDF with this image in a future PR 🤔

**Comment by akeller** [comment]
Can I nudge you for an approval @christinaausley? 😄

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
