### PR TITLE
Update manage-api-clients.md

### PR DESCRIPTION
**Pull request by jwulf**
Describe new credential environment variables

## What is the purpose of the change

The console now provides additional environment variables in client credentials. They are described in this patch.

## Are there related marketing activities

No

## When should this change go live?

ASAP

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

### CODE REVIEW

**Review by pepopowitz — APPROVED** [review]
👍 Thanks for adding this!

**Review by christinaausley — DISMISSED** [review]
Once you merge in main you should be good to go 👍

**Review by akeller — CHANGES_REQUESTED** [review]
This only covers version 8.1 but not future versions. Can you add these changes to `/docs/` so they are in the `Next` version as well?

**Comment by akeller** [comment]
I took care of this as well. Please see my general feedback regarding docs PRs on your [other PR](https://github.com/camunda/camunda-platform-docs/pull/1560#issuecomment-1344657531). Thanks!

**Pull request merged**
